// Compile a keccak-f[1600] asm backend into a staticlib that exports
// `rvr_keccak_f1600(uint64_t state[25])`. Backend selected via cargo features
// (see Cargo.toml).

use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

fn main() {
    let ctx = BuildCtx::from_env();
    let native_entry = match ctx.backend {
        Backend::Xkcp => xkcp::build(&ctx),
        Backend::Openssl => openssl::build(&ctx),
    };

    let shim_path = ctx.out_dir.join("rvr_keccak_shim.c");
    fs::write(&shim_path, shim_c(&native_entry)).expect("write shim");
    ctx.cc().file(&shim_path).compile("rvr_keccak");

    println!("cargo:rerun-if-changed=build.rs");
}

#[derive(Copy, Clone)]
enum Backend {
    Xkcp,
    Openssl,
}

struct BuildCtx {
    backend: Backend,
    manifest_dir: PathBuf,
    out_dir: PathBuf,
    target_arch: String,
    target_os: String,
    is_macos: bool,
}

impl BuildCtx {
    fn from_env() -> Self {
        let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
        let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();
        let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
        let is_macos = target_os == "macos" || target_os == "ios";
        Self {
            backend: select_backend(),
            manifest_dir,
            out_dir,
            target_arch,
            target_os,
            is_macos,
        }
    }

    fn cc(&self) -> cc::Build {
        let mut b = cc::Build::new();
        if self.is_macos {
            // GNU `ar`'s slash-member format is rejected by the macOS linker.
            b.archiver("/usr/bin/ar");
        }
        b
    }
}

fn select_backend() -> Backend {
    match (
        cfg!(feature = "backend-xkcp"),
        cfg!(feature = "backend-openssl"),
    ) {
        (true, false) => Backend::Xkcp,
        (false, true) => Backend::Openssl,
        (false, false) => panic!("keccak-ffi: enable backend-openssl or backend-xkcp"),
        (true, true) => panic!("keccak-ffi: enable exactly one backend feature"),
    }
}

fn shim_c(native_entry: &str) -> String {
    format!(
        "/* Auto-generated by build.rs. */\n\
         #include <stdint.h>\n\
         \n\
         extern void {native_entry}(uint64_t state[25]);\n\
         \n\
         void rvr_keccak_f1600(uint64_t state[25]) {{\n\
         \x20\x20\x20\x20{native_entry}(state);\n\
         }}\n"
    )
}

/// Inject `.globl LABEL` (and `_LABEL` alias on Mach-O) for each label so the
/// staticlib re-exports labels the upstream asm declares only as locals.
fn export_asm_symbols(asm: &str, labels: &[&str], is_macos: bool) -> String {
    let mut out = asm.to_string();
    for label in labels {
        let needle = format!("\n{label}:\n");
        let replacement = if is_macos {
            format!("\n.globl\t_{label}\n_{label}:\n{label}:\n")
        } else {
            format!("\n.globl\t{label}\n{label}:\n")
        };
        assert!(
            out.contains(&needle),
            "expected label `{label}:` not found in generated asm"
        );
        out = out.replace(&needle, &replacement);
    }
    out
}

/// Rewrite gas-only NEON lane notation `vN.2d[i]` to `vN.d[i]` for clang's
/// Mach-O assembler. Requires the `.2d[` to be preceded by a `vN` register
/// digit so a stray `.2d[0]` in a comment can't be mis-rewritten. Panics if
/// any unguarded match appears or if zero rewrites fire (upstream shape
/// changed). Operates on raw bytes; non-ASCII bytes pass through unsplit.
fn rewrite_xkcp_neon_lane_syntax(asm: &str) -> String {
    let bytes = asm.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut i = 0;
    let mut rewrites = 0usize;
    let mut unguarded = 0usize;
    while i < bytes.len() {
        let tail_is_lane = i + 6 <= bytes.len()
            && &bytes[i..i + 4] == b".2d["
            && (bytes[i + 4] == b'0' || bytes[i + 4] == b'1')
            && bytes[i + 5] == b']';
        if tail_is_lane {
            let guarded = i > 0 && bytes[i - 1].is_ascii_digit();
            if guarded {
                out.extend_from_slice(b".d[");
                out.push(bytes[i + 4]);
                out.push(b']');
                i += 6;
                rewrites += 1;
                continue;
            } else {
                unguarded += 1;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    assert!(unguarded == 0, "unguarded `.2d[0/1]` in XKCP NEON asm");
    assert!(
        rewrites > 0,
        "no `vN.2d[i]` rewrites; upstream shape changed?"
    );
    println!("cargo:warning=xkcp: rewrote {rewrites} `vN.2d[i]` lane tokens");
    String::from_utf8(out).expect("rewrite preserves UTF-8")
}

fn run_perl(script: &Path, flavor: &str, out_path: &Path) {
    let output = Command::new("perl")
        .arg(script)
        .arg(flavor)
        .arg(out_path)
        .output()
        .expect("perl not found");
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        panic!(
            "perl {} failed: {stderr}",
            script.file_name().unwrap().to_string_lossy()
        );
    }
    // OpenSSL/CRYPTOGAMS scripts may write to either the output file or stdout
    // depending on flavor; accept whichever produced content.
    let stdout = String::from_utf8_lossy(&output.stdout);
    if !stdout.trim().is_empty() {
        fs::write(out_path, stdout.as_bytes()).unwrap();
    }
    assert!(out_path.exists(), "asm not generated at {out_path:?}");
}

mod xkcp {
    use super::*;

    pub fn build(ctx: &BuildCtx) -> String {
        let xkcp = ctx.manifest_dir.join("xkcp");
        assert!(
            xkcp.join("lib/low/KeccakP-1600").is_dir(),
            "xkcp submodule missing. Run: git submodule update --init --recursive"
        );

        let (src_rel, native_entry) = match ctx.target_arch.as_str() {
            // AVX-512 file already exports both plain and `_`-prefix forms.
            "x86_64" => (
                "lib/low/KeccakP-1600/AVX512/KeccakP-1600-AVX512.s",
                "KeccakP1600_AVX512_Permute_24rounds",
            ),
            "aarch64" => (
                "lib/low/KeccakP-1600/ARMv8A/KeccakP-1600-armv8a-neon.s",
                "KeccakP1600_Permute_24rounds",
            ),
            arch => panic!("xkcp: unsupported target {arch}-{}", ctx.target_os),
        };

        let asm_path = ctx.out_dir.join("keccak1600_xkcp.S");
        let src = fs::read_to_string(xkcp.join(src_rel)).unwrap();
        let patched = if ctx.target_arch == "aarch64" {
            let with_globals = export_asm_symbols(&src, &[native_entry], ctx.is_macos);
            rewrite_xkcp_neon_lane_syntax(&with_globals)
        } else {
            src
        };
        fs::write(&asm_path, patched).unwrap();

        ctx.cc().file(&asm_path).compile("keccak_xkcp");
        println!("cargo:rerun-if-changed={}", xkcp.display());

        native_entry.to_string()
    }
}

mod openssl {
    use super::*;

    pub fn build(ctx: &BuildCtx) -> String {
        let openssl = ctx.manifest_dir.join("openssl");
        let armv8 = openssl.join("crypto/sha/asm/keccak1600-armv8.pl");
        let x86_64 = openssl.join("crypto/sha/asm/keccak1600-x86_64.pl");
        assert!(
            armv8.exists() && x86_64.exists(),
            "openssl submodule missing. Run: git submodule update --init --recursive"
        );

        // `+sha3` flavor enables ARMv8.2 SHA3-ext (`KeccakF1600_cext`); we use
        // it on Apple Silicon (always SHA3-capable) and skip it on Linux
        // aarch64 to avoid emitting unreachable code.
        let (script, flavor, extra_globals, native_entry) =
            match (ctx.target_arch.as_str(), ctx.target_os.as_str()) {
                ("x86_64", "macos") => (x86_64.as_path(), "macosx", &[] as &[&str], "KeccakF1600"),
                ("x86_64", _) => (x86_64.as_path(), "elf", &[] as &[&str], "KeccakF1600"),
                ("aarch64", "macos") => (
                    armv8.as_path(),
                    "ios64+sha3",
                    &["KeccakF1600_cext"][..],
                    "KeccakF1600_cext",
                ),
                ("aarch64", "linux") => (armv8.as_path(), "linux64", &[] as &[&str], "KeccakF1600"),
                (arch, os) => panic!("openssl: unsupported target {arch}-{os}"),
            };

        let asm_path = ctx.out_dir.join("keccak1600_openssl.S");
        run_perl(script, flavor, &asm_path);

        let mut labels: Vec<&str> = vec!["KeccakF1600"];
        labels.extend_from_slice(extra_globals);
        let asm = fs::read_to_string(&asm_path).unwrap();
        fs::write(&asm_path, export_asm_symbols(&asm, &labels, ctx.is_macos)).unwrap();

        // The emitted armv8 asm `#include`s `arm_arch.h` for PAC/BTI hints.
        ctx.cc()
            .include(openssl.join("crypto"))
            .file(&asm_path)
            .compile("keccak_openssl");
        println!("cargo:rerun-if-changed={}", openssl.display());

        native_entry.to_string()
    }
}
