// Compile OpenSSL's keccak-f[1600] asm backend into a staticlib that exports
// `rvr_keccak_f1600(uint64_t state[static 25])`.

use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use rvr_openvm_build::{default_compiler_command, ensure_clang_compiler};

fn main() {
    println!("cargo:rerun-if-env-changed=RVR_CC");
    println!("cargo:rerun-if-env-changed=CC");
    println!("cargo:rerun-if-env-changed=AS");
    println!("cargo:rerun-if-env-changed=CFLAGS");
    println!("cargo:rerun-if-env-changed=PATH");

    let ctx = BuildCtx::from_env();
    let native_entry = build_openssl(&ctx);

    let shim_path = ctx.out_dir.join("rvr_keccak_shim.c");
    fs::write(&shim_path, shim_c(&native_entry)).expect("write shim");
    ctx.cc().file(&shim_path).compile("rvr_keccak");

    println!("cargo:rerun-if-changed=build.rs");
}

struct BuildCtx {
    compiler: String,
    manifest_dir: PathBuf,
    out_dir: PathBuf,
    target_arch: String,
    target_os: String,
    is_macos: bool,
}

impl BuildCtx {
    fn from_env() -> Self {
        let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
        let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();
        let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
        let is_macos = target_os == "macos" || target_os == "ios";
        let compiler = default_compiler_command();
        ensure_clang_compiler(&compiler).unwrap_or_else(|e| {
            panic!(
                "\n\n\
                 rvr-openvm-ext-keccak-ffi requires clang to build its \
                 OpenSSL assembly backend.\n\
                 {e}\n\n\
                 Install clang-22 and re-run with:\n\
                   export RVR_CC=clang-22 CC=clang-22 AS=clang-22 CFLAGS=-fintegrated-as\n"
            )
        });
        Self {
            compiler,
            manifest_dir,
            out_dir,
            target_arch,
            target_os,
            is_macos,
        }
    }

    fn cc(&self) -> cc::Build {
        let mut b = cc::Build::new();
        b.compiler(&self.compiler).flag("-fintegrated-as");
        if self.is_macos {
            // GNU `ar`'s slash-member format is rejected by the macOS linker.
            b.archiver("/usr/bin/ar");
        }
        b
    }
}

fn shim_c(native_entry: &str) -> String {
    format!(
        "/* Auto-generated by build.rs. */\n\
         #include <stdint.h>\n\
         \n\
         extern void {native_entry}(uint64_t state[static 25]);\n\
         \n\
         void rvr_keccak_f1600(uint64_t state[static 25]) {{\n\
         \x20\x20\x20\x20{native_entry}(state);\n\
         }}\n"
    )
}

/// Inject `.globl LABEL` (and `_LABEL` alias on Mach-O) for each label so the
/// staticlib re-exports labels the upstream asm declares only as locals.
fn export_asm_symbols(asm: &str, labels: &[&str], is_macos: bool) -> String {
    let mut out = asm.to_string();
    for label in labels {
        let needle = format!("\n{label}:\n");
        let replacement = if is_macos {
            format!("\n.globl\t_{label}\n_{label}:\n{label}:\n")
        } else {
            format!("\n.globl\t{label}\n{label}:\n")
        };
        assert!(
            out.contains(&needle),
            "expected label `{label}:` not found in generated asm"
        );
        out = out.replace(&needle, &replacement);
    }
    out
}

fn run_perl(script: &Path, flavor: &str, out_path: &Path) {
    let output = Command::new("perl")
        .arg(script)
        .arg(flavor)
        .arg(out_path)
        .output()
        .expect("perl not found");
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        panic!(
            "perl {} failed: {stderr}",
            script.file_name().unwrap().to_string_lossy()
        );
    }
    // OpenSSL/CRYPTOGAMS scripts may write to either the output file or stdout
    // depending on flavor; accept whichever produced content.
    let stdout = String::from_utf8_lossy(&output.stdout);
    if !stdout.trim().is_empty() {
        fs::write(out_path, stdout.as_bytes()).unwrap();
    }
    assert!(out_path.exists(), "asm not generated at {out_path:?}");
}

fn build_openssl(ctx: &BuildCtx) -> String {
    let openssl = ctx.manifest_dir.join("openssl");
    let armv8 = openssl.join("crypto/sha/asm/keccak1600-armv8.pl");
    let x86_64 = openssl.join("crypto/sha/asm/keccak1600-x86_64.pl");
    assert!(
        armv8.exists() && x86_64.exists(),
        "openssl submodule missing. Run: git submodule update --init extensions/keccak256/rvr/ffi/openssl"
    );

    // `+sha3` flavor enables ARMv8.2 SHA3-ext (`KeccakF1600_cext`); we use
    // it on Apple Silicon (always SHA3-capable) and skip it on Linux aarch64
    // to avoid emitting unreachable code.
    let (script, flavor, extra_globals, native_entry) =
        match (ctx.target_arch.as_str(), ctx.target_os.as_str()) {
            ("x86_64", "macos") => (x86_64.as_path(), "macosx", &[] as &[&str], "KeccakF1600"),
            ("x86_64", "linux") => (x86_64.as_path(), "linux64", &[] as &[&str], "KeccakF1600"),
            ("aarch64", "macos") => (
                armv8.as_path(),
                "ios64+sha3",
                &["KeccakF1600_cext"][..],
                "KeccakF1600_cext",
            ),
            ("aarch64", "linux") => (armv8.as_path(), "linux64", &[] as &[&str], "KeccakF1600"),
            (arch, os) => panic!("openssl: unsupported target {arch}-{os}"),
        };

    let asm_path = ctx.out_dir.join("keccak1600_openssl.S");
    run_perl(script, flavor, &asm_path);

    let mut labels: Vec<&str> = vec!["KeccakF1600"];
    labels.extend_from_slice(extra_globals);
    let asm = fs::read_to_string(&asm_path).unwrap();
    fs::write(&asm_path, export_asm_symbols(&asm, &labels, ctx.is_macos)).unwrap();

    // The emitted armv8 asm `#include`s `arm_arch.h` for PAC/BTI hints.
    ctx.cc()
        .include(openssl.join("crypto"))
        .file(&asm_path)
        .compile("keccak_openssl");
    println!("cargo:rerun-if-changed={}", armv8.display());
    println!("cargo:rerun-if-changed={}", x86_64.display());
    println!(
        "cargo:rerun-if-changed={}",
        openssl.join("crypto/arm_arch.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        openssl.join("crypto/perlasm/arm-xlate.pl").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        openssl.join("crypto/perlasm/x86_64-xlate.pl").display()
    );

    native_entry.to_string()
}
