images:
  arm64-rust-riscv-dev-32gb:
    platform: "linux"
    arch: "arm64"
    owner: "405894839083"
    name: "arm64-rust-riscv-dev-32gb"
    ami: "ami-040a96edd406c9478"

runners:
  cpu-small-arm64:
    family:
      [
        "c9g.4xlarge",
        "c8g.4xlarge",
        "m9g.4xlarge",
        "m8g.4xlarge",
      ]
    image: ubuntu24-full-arm64
    volume: 80gb

  cpu-medium-arm64:
    family:
      [
        "c9g.8xlarge",
        "c8g.8xlarge",
        "m9g.8xlarge",
        "m8g.8xlarge",
      ]
    image: ubuntu24-full-arm64
    volume: 80gb

  cpu-small-x64:
    family:
      [
        "c8i-flex.4xlarge",
        "c8i.4xlarge",
        "c8a.4xlarge",
        "c7i.4xlarge",
        "c7a.4xlarge",
      ]
    image: ubuntu24-full-x64
    volume: 80gb

  cpu-medium-x64:
    family:
      [
        "c8i-flex.8xlarge",
        "c8i.8xlarge",
        "c8a.8xlarge",
        "c7i.8xlarge",
        "c7a.8xlarge",
      ]
    image: ubuntu24-full-x64
    volume: 80gb

  # runners for running tests
  test-gpu-nvidia:
    family: ["g7.4xlarge", "g6.4xlarge", "g5.4xlarge"]
    image: ubuntu24-gpu-x64
    volume: 40gb
    spot: price-capacity-optimized
    extras: s3-cache
    preinstall: |
      echo 'CUDA_ARCH=86,89,120' >> $GITHUB_ENV
