// Lean compiler output
// Module: ImportGraph.Tools.RedundantImports
// Imports: public import Init public meta import Init public meta import Lean.Elab.Command public meta import Lean.Widget.UserWidget public meta import ImportGraph.Imports.Redundant
#include <lean/lean.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined(__GNUC__) && !defined(__CLANG__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#ifdef __cplusplus
extern "C" {
#endif
lean_object* l_Lean_Name_mkStr1(lean_object*);
extern lean_object* l_Lean_Elab_unsupportedSyntaxExceptionId;
uint8_t l_Lean_Syntax_isOfKind(lean_object*, lean_object*);
lean_object* lp_importGraph_redundantImports___boxed(lean_object*, lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_Elab_Command_liftCoreM___redArg(lean_object*, lean_object*, lean_object*);
lean_object* l_Lean_MessageData_ofFormat(lean_object*);
lean_object* l_Lean_Name_toString(lean_object*, uint8_t);
lean_object* l_Lean_Elab_Command_getRef___redArg(lean_object*);
lean_object* l_Lean_Elab_Command_getScope___redArg(lean_object*);
lean_object* lean_st_ref_take(lean_object*);
lean_object* l_Lean_MessageLog_add(lean_object*, lean_object*);
lean_object* lean_st_ref_set(lean_object*, lean_object*);
lean_object* l___private_Lean_Log_0__Lean_MessageData_appendDescriptionWidgetIfNamed(lean_object*);
lean_object* lean_st_ref_get(lean_object*);
extern lean_object* l_Lean_Elab_Command_instInhabitedScope_default;
lean_object* l_List_head_x21___redArg(lean_object*, lean_object*);
lean_object* l_Lean_PersistentHashMap_mkEmptyEntriesArray(lean_object*, lean_object*);
lean_object* lean_mk_empty_array_with_capacity(lean_object*);
lean_object* l_Lean_FileMap_toPosition(lean_object*, lean_object*);
uint8_t lean_string_dec_eq(lean_object*, lean_object*);
uint8_t l_Lean_MessageData_hasTag(lean_object*, lean_object*);
lean_object* l_Lean_Syntax_getTailPos_x3f(lean_object*, uint8_t);
lean_object* l_Lean_replaceRef(lean_object*, lean_object*);
lean_object* l_Lean_Syntax_getPos_x3f(lean_object*, uint8_t);
uint8_t l_Lean_instBEqMessageSeverity_beq(uint8_t, uint8_t);
extern lean_object* l_Lean_warningAsError;
lean_object* l_Std_DTreeMap_Internal_Impl_Const_get_x3f___at___00Lean_NameMap_find_x3f_spec__0___redArg(lean_object*, lean_object*);
uint8_t l_Lean_MessageData_hasSyntheticSorry(lean_object*);
static const lean_string_object lp_importGraph_command_x23redundant__imports___closed__0_value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 26, .m_capacity = 26, .m_length = 25, .m_data = "command#redundant_imports"};
static const lean_object* lp_importGraph_command_x23redundant__imports___closed__0 = (const lean_object*)&lp_importGraph_command_x23redundant__imports___closed__0_value;
static const lean_ctor_object lp_importGraph_command_x23redundant__imports___closed__1_value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_ctor_object) + sizeof(void*)*2 + 8, .m_other = 2, .m_tag = 1}, .m_objs = {((lean_object*)(((size_t)(0) << 1) | 1)),((lean_object*)&lp_importGraph_command_x23redundant__imports___closed__0_value),LEAN_SCALAR_PTR_LITERAL(0, 219, 145, 219, 145, 108, 96, 96)}};
static const lean_object* lp_importGraph_command_x23redundant__imports___closed__1 = (const lean_object*)&lp_importGraph_command_x23redundant__imports___closed__1_value;
static const lean_string_object lp_importGraph_command_x23redundant__imports___closed__2_value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 19, .m_capacity = 19, .m_length = 18, .m_data = "#redundant_imports"};
static const lean_object* lp_importGraph_command_x23redundant__imports___closed__2 = (const lean_object*)&lp_importGraph_command_x23redundant__imports___closed__2_value;
static const lean_ctor_object lp_importGraph_command_x23redundant__imports___closed__3_value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_ctor_object) + sizeof(void*)*1 + 0, .m_other = 1, .m_tag = 5}, .m_objs = {((lean_object*)&lp_importGraph_command_x23redundant__imports___closed__2_value)}};
static const lean_object* lp_importGraph_command_x23redundant__imports___closed__3 = (const lean_object*)&lp_importGraph_command_x23redundant__imports___closed__3_value;
static const lean_ctor_object lp_importGraph_command_x23redundant__imports___closed__4_value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_ctor_object) + sizeof(void*)*3 + 0, .m_other = 3, .m_tag = 3}, .m_objs = {((lean_object*)&lp_importGraph_command_x23redundant__imports___closed__1_value),((lean_object*)(((size_t)(1024) << 1) | 1)),((lean_object*)&lp_importGraph_command_x23redundant__imports___closed__3_value)}};
static const lean_object* lp_importGraph_command_x23redundant__imports___closed__4 = (const lean_object*)&lp_importGraph_command_x23redundant__imports___closed__4_value;
LEAN_EXPORT const lean_object* lp_importGraph_command_x23redundant__imports = (const lean_object*)&lp_importGraph_command_x23redundant__imports___closed__4_value;
static lean_once_cell_t lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg___closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg___closed__0;
LEAN_EXPORT lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg();
LEAN_EXPORT lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg___boxed(lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0(lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___boxed(lean_object*, lean_object*, lean_object*, lean_object*);
static lean_once_cell_t lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__0_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__0;
static lean_once_cell_t lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1;
static lean_once_cell_t lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__2_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__2;
static lean_once_cell_t lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__3_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__3;
static lean_once_cell_t lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__4_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__4;
static lean_once_cell_t lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__5_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__5;
LEAN_EXPORT lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg(lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___boxed(lean_object*, lean_object*, lean_object*);
LEAN_EXPORT uint8_t lp_importGraph_Lean_Option_get___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__7(lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_Option_get___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__7___boxed(lean_object*, lean_object*);
static const lean_string_object lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0___closed__0_value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 6, .m_capacity = 6, .m_length = 5, .m_data = "trace"};
static const lean_object* lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0___closed__0 = (const lean_object*)&lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0___closed__0_value;
LEAN_EXPORT uint8_t lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0(uint8_t, uint8_t, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0___boxed(lean_object*, lean_object*, lean_object*);
static const lean_string_object lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___closed__0_value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 1, .m_capacity = 1, .m_length = 0, .m_data = ""};
static const lean_object* lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___closed__0 = (const lean_object*)&lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___closed__0_value;
LEAN_EXPORT lean_object* lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5(lean_object*, lean_object*, uint8_t, uint8_t, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4(lean_object*, uint8_t, uint8_t, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3(lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3___boxed(lean_object*, lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_List_foldl___at___00Std_Format_joinSep___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__2_spec__2(lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Std_Format_joinSep___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__2(lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Std_DTreeMap_Internal_Impl_foldrM___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__1(lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Std_DTreeMap_Internal_Impl_foldrM___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__1___boxed(lean_object*, lean_object*);
static const lean_closure_object lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__0_value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_closure_object) + sizeof(void*)*1, .m_other = 0, .m_tag = 245}, .m_fun = (void*)lp_importGraph_redundantImports___boxed, .m_arity = 4, .m_num_fixed = 1, .m_objs = {((lean_object*)(((size_t)(0) << 1) | 1))} };
static const lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__0 = (const lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__0_value;
static const lean_string_object lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__1_value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 53, .m_capacity = 53, .m_length = 52, .m_data = "Found the following transitively redundant imports:\n"};
static const lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__1 = (const lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__1_value;
static const lean_ctor_object lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__2_value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_ctor_object) + sizeof(void*)*1 + 0, .m_other = 1, .m_tag = 3}, .m_objs = {((lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__1_value)}};
static const lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__2 = (const lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__2_value;
static lean_once_cell_t lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__3_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__3;
static const lean_string_object lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__4_value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 2, .m_capacity = 2, .m_length = 1, .m_data = "\n"};
static const lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__4 = (const lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__4_value;
static const lean_ctor_object lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__5_value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_ctor_object) + sizeof(void*)*1 + 0, .m_other = 1, .m_tag = 3}, .m_objs = {((lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__4_value)}};
static const lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__5 = (const lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__5_value;
static const lean_string_object lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__6_value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 41, .m_capacity = 41, .m_length = 40, .m_data = "No transitively redundant imports found."};
static const lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__6 = (const lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__6_value;
static const lean_ctor_object lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__7_value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_ctor_object) + sizeof(void*)*1 + 0, .m_other = 1, .m_tag = 3}, .m_objs = {((lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__6_value)}};
static const lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__7 = (const lean_object*)&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__7_value;
static lean_once_cell_t lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__8_once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__8;
LEAN_EXPORT lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1(lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___boxed(lean_object*, lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6(lean_object*, lean_object*, lean_object*);
LEAN_EXPORT lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___boxed(lean_object*, lean_object*, lean_object*, lean_object*);
static lean_object* _init_lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg___closed__0(void){
_start:
{
lean_object* v___x_12_; lean_object* v___x_13_; lean_object* v___x_14_; 
v___x_12_ = lean_box(0);
v___x_13_ = l_Lean_Elab_unsupportedSyntaxExceptionId;
v___x_14_ = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(v___x_14_, 0, v___x_13_);
lean_ctor_set(v___x_14_, 1, v___x_12_);
return v___x_14_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg(){
_start:
{
lean_object* v___x_16_; lean_object* v___x_17_; 
v___x_16_ = lean_obj_once(&lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg___closed__0, &lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg___closed__0_once, _init_lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg___closed__0);
v___x_17_ = lean_alloc_ctor(1, 1, 0);
lean_ctor_set(v___x_17_, 0, v___x_16_);
return v___x_17_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg___boxed(lean_object* v___y_18_){
_start:
{
lean_object* v_res_19_; 
v_res_19_ = lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg();
return v_res_19_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0(lean_object* v_00_u03b1_20_, lean_object* v___y_21_, lean_object* v___y_22_){
_start:
{
lean_object* v___x_24_; 
v___x_24_ = lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg();
return v___x_24_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___boxed(lean_object* v_00_u03b1_25_, lean_object* v___y_26_, lean_object* v___y_27_, lean_object* v___y_28_){
_start:
{
lean_object* v_res_29_; 
v_res_29_ = lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0(v_00_u03b1_25_, v___y_26_, v___y_27_);
lean_dec(v___y_27_);
lean_dec_ref(v___y_26_);
return v_res_29_;
}
}
static lean_object* _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__0(void){
_start:
{
lean_object* v___x_30_; 
v___x_30_ = l_Lean_PersistentHashMap_mkEmptyEntriesArray(lean_box(0), lean_box(0));
return v___x_30_;
}
}
static lean_object* _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1(void){
_start:
{
lean_object* v___x_31_; lean_object* v___x_32_; 
v___x_31_ = lean_obj_once(&lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__0, &lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__0_once, _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__0);
v___x_32_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_32_, 0, v___x_31_);
return v___x_32_;
}
}
static lean_object* _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__2(void){
_start:
{
lean_object* v___x_33_; lean_object* v___x_34_; lean_object* v___x_35_; 
v___x_33_ = lean_obj_once(&lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1, &lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1_once, _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1);
v___x_34_ = lean_unsigned_to_nat(0u);
v___x_35_ = lean_alloc_ctor(0, 10, 0);
lean_ctor_set(v___x_35_, 0, v___x_34_);
lean_ctor_set(v___x_35_, 1, v___x_34_);
lean_ctor_set(v___x_35_, 2, v___x_34_);
lean_ctor_set(v___x_35_, 3, v___x_34_);
lean_ctor_set(v___x_35_, 4, v___x_33_);
lean_ctor_set(v___x_35_, 5, v___x_33_);
lean_ctor_set(v___x_35_, 6, v___x_33_);
lean_ctor_set(v___x_35_, 7, v___x_33_);
lean_ctor_set(v___x_35_, 8, v___x_33_);
lean_ctor_set(v___x_35_, 9, v___x_33_);
return v___x_35_;
}
}
static lean_object* _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__3(void){
_start:
{
lean_object* v___x_36_; lean_object* v___x_37_; lean_object* v___x_38_; 
v___x_36_ = lean_unsigned_to_nat(32u);
v___x_37_ = lean_mk_empty_array_with_capacity(v___x_36_);
v___x_38_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_38_, 0, v___x_37_);
return v___x_38_;
}
}
static lean_object* _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__4(void){
_start:
{
size_t v___x_39_; lean_object* v___x_40_; lean_object* v___x_41_; lean_object* v___x_42_; lean_object* v___x_43_; lean_object* v___x_44_; 
v___x_39_ = ((size_t)5ULL);
v___x_40_ = lean_unsigned_to_nat(0u);
v___x_41_ = lean_unsigned_to_nat(32u);
v___x_42_ = lean_mk_empty_array_with_capacity(v___x_41_);
v___x_43_ = lean_obj_once(&lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__3, &lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__3_once, _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__3);
v___x_44_ = lean_alloc_ctor(0, 4, sizeof(size_t)*1);
lean_ctor_set(v___x_44_, 0, v___x_43_);
lean_ctor_set(v___x_44_, 1, v___x_42_);
lean_ctor_set(v___x_44_, 2, v___x_40_);
lean_ctor_set(v___x_44_, 3, v___x_40_);
lean_ctor_set_usize(v___x_44_, 4, v___x_39_);
return v___x_44_;
}
}
static lean_object* _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__5(void){
_start:
{
lean_object* v___x_45_; lean_object* v___x_46_; lean_object* v___x_47_; lean_object* v___x_48_; 
v___x_45_ = lean_box(1);
v___x_46_ = lean_obj_once(&lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__4, &lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__4_once, _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__4);
v___x_47_ = lean_obj_once(&lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1, &lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1_once, _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__1);
v___x_48_ = lean_alloc_ctor(0, 3, 0);
lean_ctor_set(v___x_48_, 0, v___x_47_);
lean_ctor_set(v___x_48_, 1, v___x_46_);
lean_ctor_set(v___x_48_, 2, v___x_45_);
return v___x_48_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg(lean_object* v_msgData_49_, lean_object* v___y_50_){
_start:
{
lean_object* v___x_52_; lean_object* v_env_53_; lean_object* v___x_54_; lean_object* v_scopes_55_; lean_object* v___x_56_; lean_object* v___x_57_; lean_object* v_opts_58_; lean_object* v___x_59_; lean_object* v___x_60_; lean_object* v___x_61_; lean_object* v___x_62_; lean_object* v___x_63_; 
v___x_52_ = lean_st_ref_get(v___y_50_);
v_env_53_ = lean_ctor_get(v___x_52_, 0);
lean_inc_ref(v_env_53_);
lean_dec(v___x_52_);
v___x_54_ = lean_st_ref_get(v___y_50_);
v_scopes_55_ = lean_ctor_get(v___x_54_, 2);
lean_inc(v_scopes_55_);
lean_dec(v___x_54_);
v___x_56_ = l_Lean_Elab_Command_instInhabitedScope_default;
v___x_57_ = l_List_head_x21___redArg(v___x_56_, v_scopes_55_);
lean_dec(v_scopes_55_);
v_opts_58_ = lean_ctor_get(v___x_57_, 1);
lean_inc_ref(v_opts_58_);
lean_dec(v___x_57_);
v___x_59_ = lean_obj_once(&lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__2, &lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__2_once, _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__2);
v___x_60_ = lean_obj_once(&lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__5, &lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__5_once, _init_lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___closed__5);
v___x_61_ = lean_alloc_ctor(0, 4, 0);
lean_ctor_set(v___x_61_, 0, v_env_53_);
lean_ctor_set(v___x_61_, 1, v___x_59_);
lean_ctor_set(v___x_61_, 2, v___x_60_);
lean_ctor_set(v___x_61_, 3, v_opts_58_);
v___x_62_ = lean_alloc_ctor(3, 2, 0);
lean_ctor_set(v___x_62_, 0, v___x_61_);
lean_ctor_set(v___x_62_, 1, v_msgData_49_);
v___x_63_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_63_, 0, v___x_62_);
return v___x_63_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg___boxed(lean_object* v_msgData_64_, lean_object* v___y_65_, lean_object* v___y_66_){
_start:
{
lean_object* v_res_67_; 
v_res_67_ = lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg(v_msgData_64_, v___y_65_);
lean_dec(v___y_65_);
return v_res_67_;
}
}
LEAN_EXPORT uint8_t lp_importGraph_Lean_Option_get___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__7(lean_object* v_opts_68_, lean_object* v_opt_69_){
_start:
{
lean_object* v_name_70_; lean_object* v_defValue_71_; lean_object* v_map_72_; lean_object* v___x_73_; 
v_name_70_ = lean_ctor_get(v_opt_69_, 0);
v_defValue_71_ = lean_ctor_get(v_opt_69_, 1);
v_map_72_ = lean_ctor_get(v_opts_68_, 0);
v___x_73_ = l_Std_DTreeMap_Internal_Impl_Const_get_x3f___at___00Lean_NameMap_find_x3f_spec__0___redArg(v_map_72_, v_name_70_);
if (lean_obj_tag(v___x_73_) == 0)
{
uint8_t v___x_74_; 
v___x_74_ = lean_unbox(v_defValue_71_);
return v___x_74_;
}
else
{
lean_object* v_val_75_; 
v_val_75_ = lean_ctor_get(v___x_73_, 0);
lean_inc(v_val_75_);
lean_dec_ref_known(v___x_73_, 1);
if (lean_obj_tag(v_val_75_) == 1)
{
uint8_t v_v_76_; 
v_v_76_ = lean_ctor_get_uint8(v_val_75_, 0);
lean_dec_ref_known(v_val_75_, 0);
return v_v_76_;
}
else
{
uint8_t v___x_77_; 
lean_dec(v_val_75_);
v___x_77_ = lean_unbox(v_defValue_71_);
return v___x_77_;
}
}
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_Option_get___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__7___boxed(lean_object* v_opts_78_, lean_object* v_opt_79_){
_start:
{
uint8_t v_res_80_; lean_object* v_r_81_; 
v_res_80_ = lp_importGraph_Lean_Option_get___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__7(v_opts_78_, v_opt_79_);
lean_dec_ref(v_opt_79_);
lean_dec_ref(v_opts_78_);
v_r_81_ = lean_box(v_res_80_);
return v_r_81_;
}
}
LEAN_EXPORT uint8_t lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0(uint8_t v___y_83_, uint8_t v_suppressElabErrors_84_, lean_object* v_x_85_){
_start:
{
if (lean_obj_tag(v_x_85_) == 1)
{
lean_object* v_pre_86_; 
v_pre_86_ = lean_ctor_get(v_x_85_, 0);
if (lean_obj_tag(v_pre_86_) == 0)
{
lean_object* v_str_87_; lean_object* v___x_88_; uint8_t v___x_89_; 
v_str_87_ = lean_ctor_get(v_x_85_, 1);
v___x_88_ = ((lean_object*)(lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0___closed__0));
v___x_89_ = lean_string_dec_eq(v_str_87_, v___x_88_);
if (v___x_89_ == 0)
{
return v___y_83_;
}
else
{
return v_suppressElabErrors_84_;
}
}
else
{
return v___y_83_;
}
}
else
{
return v___y_83_;
}
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0___boxed(lean_object* v___y_90_, lean_object* v_suppressElabErrors_91_, lean_object* v_x_92_){
_start:
{
uint8_t v___y_3266__boxed_93_; uint8_t v_suppressElabErrors_boxed_94_; uint8_t v_res_95_; lean_object* v_r_96_; 
v___y_3266__boxed_93_ = lean_unbox(v___y_90_);
v_suppressElabErrors_boxed_94_ = lean_unbox(v_suppressElabErrors_91_);
v_res_95_ = lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0(v___y_3266__boxed_93_, v_suppressElabErrors_boxed_94_, v_x_92_);
lean_dec(v_x_92_);
v_r_96_ = lean_box(v_res_95_);
return v_r_96_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5(lean_object* v_ref_98_, lean_object* v_msgData_99_, uint8_t v_severity_100_, uint8_t v_isSilent_101_, lean_object* v___y_102_, lean_object* v___y_103_){
_start:
{
lean_object* v___y_106_; uint8_t v___y_107_; lean_object* v___y_108_; uint8_t v___y_109_; lean_object* v___y_110_; lean_object* v___y_111_; lean_object* v___y_112_; lean_object* v___y_113_; uint8_t v___y_170_; uint8_t v___y_171_; lean_object* v___y_172_; uint8_t v___y_173_; lean_object* v___y_174_; uint8_t v___y_198_; uint8_t v___y_199_; uint8_t v___y_200_; lean_object* v___y_201_; lean_object* v___y_202_; uint8_t v___y_206_; uint8_t v___y_207_; uint8_t v___y_208_; uint8_t v___x_223_; uint8_t v___y_225_; uint8_t v___y_226_; uint8_t v___y_227_; uint8_t v___y_229_; uint8_t v___x_241_; 
v___x_223_ = 2;
v___x_241_ = l_Lean_instBEqMessageSeverity_beq(v_severity_100_, v___x_223_);
if (v___x_241_ == 0)
{
v___y_229_ = v___x_241_;
goto v___jp_228_;
}
else
{
uint8_t v___x_242_; 
lean_inc_ref(v_msgData_99_);
v___x_242_ = l_Lean_MessageData_hasSyntheticSorry(v_msgData_99_);
v___y_229_ = v___x_242_;
goto v___jp_228_;
}
v___jp_105_:
{
lean_object* v___x_114_; 
v___x_114_ = l_Lean_Elab_Command_getScope___redArg(v___y_113_);
if (lean_obj_tag(v___x_114_) == 0)
{
lean_object* v_a_115_; lean_object* v___x_116_; 
v_a_115_ = lean_ctor_get(v___x_114_, 0);
lean_inc(v_a_115_);
lean_dec_ref_known(v___x_114_, 1);
v___x_116_ = l_Lean_Elab_Command_getScope___redArg(v___y_113_);
if (lean_obj_tag(v___x_116_) == 0)
{
lean_object* v_a_117_; lean_object* v___x_119_; uint8_t v_isShared_120_; uint8_t v_isSharedCheck_152_; 
v_a_117_ = lean_ctor_get(v___x_116_, 0);
v_isSharedCheck_152_ = !lean_is_exclusive(v___x_116_);
if (v_isSharedCheck_152_ == 0)
{
v___x_119_ = v___x_116_;
v_isShared_120_ = v_isSharedCheck_152_;
goto v_resetjp_118_;
}
else
{
lean_inc(v_a_117_);
lean_dec(v___x_116_);
v___x_119_ = lean_box(0);
v_isShared_120_ = v_isSharedCheck_152_;
goto v_resetjp_118_;
}
v_resetjp_118_:
{
lean_object* v___x_121_; lean_object* v_currNamespace_122_; lean_object* v_openDecls_123_; lean_object* v_env_124_; lean_object* v_messages_125_; lean_object* v_scopes_126_; lean_object* v_usedQuotCtxts_127_; lean_object* v_nextMacroScope_128_; lean_object* v_maxRecDepth_129_; lean_object* v_ngen_130_; lean_object* v_auxDeclNGen_131_; lean_object* v_infoState_132_; lean_object* v_traceState_133_; lean_object* v_snapshotTasks_134_; lean_object* v_prevLinterStates_135_; lean_object* v___x_137_; uint8_t v_isShared_138_; uint8_t v_isSharedCheck_151_; 
v___x_121_ = lean_st_ref_take(v___y_113_);
v_currNamespace_122_ = lean_ctor_get(v_a_115_, 2);
lean_inc(v_currNamespace_122_);
lean_dec(v_a_115_);
v_openDecls_123_ = lean_ctor_get(v_a_117_, 3);
lean_inc(v_openDecls_123_);
lean_dec(v_a_117_);
v_env_124_ = lean_ctor_get(v___x_121_, 0);
v_messages_125_ = lean_ctor_get(v___x_121_, 1);
v_scopes_126_ = lean_ctor_get(v___x_121_, 2);
v_usedQuotCtxts_127_ = lean_ctor_get(v___x_121_, 3);
v_nextMacroScope_128_ = lean_ctor_get(v___x_121_, 4);
v_maxRecDepth_129_ = lean_ctor_get(v___x_121_, 5);
v_ngen_130_ = lean_ctor_get(v___x_121_, 6);
v_auxDeclNGen_131_ = lean_ctor_get(v___x_121_, 7);
v_infoState_132_ = lean_ctor_get(v___x_121_, 8);
v_traceState_133_ = lean_ctor_get(v___x_121_, 9);
v_snapshotTasks_134_ = lean_ctor_get(v___x_121_, 10);
v_prevLinterStates_135_ = lean_ctor_get(v___x_121_, 11);
v_isSharedCheck_151_ = !lean_is_exclusive(v___x_121_);
if (v_isSharedCheck_151_ == 0)
{
v___x_137_ = v___x_121_;
v_isShared_138_ = v_isSharedCheck_151_;
goto v_resetjp_136_;
}
else
{
lean_inc(v_prevLinterStates_135_);
lean_inc(v_snapshotTasks_134_);
lean_inc(v_traceState_133_);
lean_inc(v_infoState_132_);
lean_inc(v_auxDeclNGen_131_);
lean_inc(v_ngen_130_);
lean_inc(v_maxRecDepth_129_);
lean_inc(v_nextMacroScope_128_);
lean_inc(v_usedQuotCtxts_127_);
lean_inc(v_scopes_126_);
lean_inc(v_messages_125_);
lean_inc(v_env_124_);
lean_dec(v___x_121_);
v___x_137_ = lean_box(0);
v_isShared_138_ = v_isSharedCheck_151_;
goto v_resetjp_136_;
}
v_resetjp_136_:
{
lean_object* v___x_139_; lean_object* v___x_140_; lean_object* v___x_141_; lean_object* v___x_142_; lean_object* v___x_144_; 
v___x_139_ = lean_alloc_ctor(0, 2, 0);
lean_ctor_set(v___x_139_, 0, v_currNamespace_122_);
lean_ctor_set(v___x_139_, 1, v_openDecls_123_);
v___x_140_ = lean_alloc_ctor(4, 2, 0);
lean_ctor_set(v___x_140_, 0, v___x_139_);
lean_ctor_set(v___x_140_, 1, v___y_110_);
lean_inc_ref(v___y_106_);
lean_inc_ref(v___y_111_);
v___x_141_ = lean_alloc_ctor(0, 5, 3);
lean_ctor_set(v___x_141_, 0, v___y_111_);
lean_ctor_set(v___x_141_, 1, v___y_112_);
lean_ctor_set(v___x_141_, 2, v___y_108_);
lean_ctor_set(v___x_141_, 3, v___y_106_);
lean_ctor_set(v___x_141_, 4, v___x_140_);
lean_ctor_set_uint8(v___x_141_, sizeof(void*)*5, v___y_109_);
lean_ctor_set_uint8(v___x_141_, sizeof(void*)*5 + 1, v___y_107_);
lean_ctor_set_uint8(v___x_141_, sizeof(void*)*5 + 2, v_isSilent_101_);
v___x_142_ = l_Lean_MessageLog_add(v___x_141_, v_messages_125_);
if (v_isShared_138_ == 0)
{
lean_ctor_set(v___x_137_, 1, v___x_142_);
v___x_144_ = v___x_137_;
goto v_reusejp_143_;
}
else
{
lean_object* v_reuseFailAlloc_150_; 
v_reuseFailAlloc_150_ = lean_alloc_ctor(0, 12, 0);
lean_ctor_set(v_reuseFailAlloc_150_, 0, v_env_124_);
lean_ctor_set(v_reuseFailAlloc_150_, 1, v___x_142_);
lean_ctor_set(v_reuseFailAlloc_150_, 2, v_scopes_126_);
lean_ctor_set(v_reuseFailAlloc_150_, 3, v_usedQuotCtxts_127_);
lean_ctor_set(v_reuseFailAlloc_150_, 4, v_nextMacroScope_128_);
lean_ctor_set(v_reuseFailAlloc_150_, 5, v_maxRecDepth_129_);
lean_ctor_set(v_reuseFailAlloc_150_, 6, v_ngen_130_);
lean_ctor_set(v_reuseFailAlloc_150_, 7, v_auxDeclNGen_131_);
lean_ctor_set(v_reuseFailAlloc_150_, 8, v_infoState_132_);
lean_ctor_set(v_reuseFailAlloc_150_, 9, v_traceState_133_);
lean_ctor_set(v_reuseFailAlloc_150_, 10, v_snapshotTasks_134_);
lean_ctor_set(v_reuseFailAlloc_150_, 11, v_prevLinterStates_135_);
v___x_144_ = v_reuseFailAlloc_150_;
goto v_reusejp_143_;
}
v_reusejp_143_:
{
lean_object* v___x_145_; lean_object* v___x_146_; lean_object* v___x_148_; 
v___x_145_ = lean_st_ref_set(v___y_113_, v___x_144_);
v___x_146_ = lean_box(0);
if (v_isShared_120_ == 0)
{
lean_ctor_set(v___x_119_, 0, v___x_146_);
v___x_148_ = v___x_119_;
goto v_reusejp_147_;
}
else
{
lean_object* v_reuseFailAlloc_149_; 
v_reuseFailAlloc_149_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v_reuseFailAlloc_149_, 0, v___x_146_);
v___x_148_ = v_reuseFailAlloc_149_;
goto v_reusejp_147_;
}
v_reusejp_147_:
{
return v___x_148_;
}
}
}
}
}
else
{
lean_object* v_a_153_; lean_object* v___x_155_; uint8_t v_isShared_156_; uint8_t v_isSharedCheck_160_; 
lean_dec(v_a_115_);
lean_dec_ref(v___y_112_);
lean_dec_ref(v___y_110_);
lean_dec(v___y_108_);
v_a_153_ = lean_ctor_get(v___x_116_, 0);
v_isSharedCheck_160_ = !lean_is_exclusive(v___x_116_);
if (v_isSharedCheck_160_ == 0)
{
v___x_155_ = v___x_116_;
v_isShared_156_ = v_isSharedCheck_160_;
goto v_resetjp_154_;
}
else
{
lean_inc(v_a_153_);
lean_dec(v___x_116_);
v___x_155_ = lean_box(0);
v_isShared_156_ = v_isSharedCheck_160_;
goto v_resetjp_154_;
}
v_resetjp_154_:
{
lean_object* v___x_158_; 
if (v_isShared_156_ == 0)
{
v___x_158_ = v___x_155_;
goto v_reusejp_157_;
}
else
{
lean_object* v_reuseFailAlloc_159_; 
v_reuseFailAlloc_159_ = lean_alloc_ctor(1, 1, 0);
lean_ctor_set(v_reuseFailAlloc_159_, 0, v_a_153_);
v___x_158_ = v_reuseFailAlloc_159_;
goto v_reusejp_157_;
}
v_reusejp_157_:
{
return v___x_158_;
}
}
}
}
else
{
lean_object* v_a_161_; lean_object* v___x_163_; uint8_t v_isShared_164_; uint8_t v_isSharedCheck_168_; 
lean_dec_ref(v___y_112_);
lean_dec_ref(v___y_110_);
lean_dec(v___y_108_);
v_a_161_ = lean_ctor_get(v___x_114_, 0);
v_isSharedCheck_168_ = !lean_is_exclusive(v___x_114_);
if (v_isSharedCheck_168_ == 0)
{
v___x_163_ = v___x_114_;
v_isShared_164_ = v_isSharedCheck_168_;
goto v_resetjp_162_;
}
else
{
lean_inc(v_a_161_);
lean_dec(v___x_114_);
v___x_163_ = lean_box(0);
v_isShared_164_ = v_isSharedCheck_168_;
goto v_resetjp_162_;
}
v_resetjp_162_:
{
lean_object* v___x_166_; 
if (v_isShared_164_ == 0)
{
v___x_166_ = v___x_163_;
goto v_reusejp_165_;
}
else
{
lean_object* v_reuseFailAlloc_167_; 
v_reuseFailAlloc_167_ = lean_alloc_ctor(1, 1, 0);
lean_ctor_set(v_reuseFailAlloc_167_, 0, v_a_161_);
v___x_166_ = v_reuseFailAlloc_167_;
goto v_reusejp_165_;
}
v_reusejp_165_:
{
return v___x_166_;
}
}
}
}
v___jp_169_:
{
lean_object* v_fileName_175_; lean_object* v_fileMap_176_; uint8_t v_suppressElabErrors_177_; lean_object* v___x_178_; lean_object* v___x_179_; lean_object* v_a_180_; lean_object* v___x_182_; uint8_t v_isShared_183_; uint8_t v_isSharedCheck_196_; 
v_fileName_175_ = lean_ctor_get(v___y_102_, 0);
v_fileMap_176_ = lean_ctor_get(v___y_102_, 1);
v_suppressElabErrors_177_ = lean_ctor_get_uint8(v___y_102_, sizeof(void*)*10);
v___x_178_ = l___private_Lean_Log_0__Lean_MessageData_appendDescriptionWidgetIfNamed(v_msgData_99_);
v___x_179_ = lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg(v___x_178_, v___y_103_);
v_a_180_ = lean_ctor_get(v___x_179_, 0);
v_isSharedCheck_196_ = !lean_is_exclusive(v___x_179_);
if (v_isSharedCheck_196_ == 0)
{
v___x_182_ = v___x_179_;
v_isShared_183_ = v_isSharedCheck_196_;
goto v_resetjp_181_;
}
else
{
lean_inc(v_a_180_);
lean_dec(v___x_179_);
v___x_182_ = lean_box(0);
v_isShared_183_ = v_isSharedCheck_196_;
goto v_resetjp_181_;
}
v_resetjp_181_:
{
lean_object* v___x_184_; lean_object* v___x_185_; lean_object* v___x_186_; lean_object* v___x_187_; 
lean_inc_ref_n(v_fileMap_176_, 2);
v___x_184_ = l_Lean_FileMap_toPosition(v_fileMap_176_, v___y_172_);
lean_dec(v___y_172_);
v___x_185_ = l_Lean_FileMap_toPosition(v_fileMap_176_, v___y_174_);
lean_dec(v___y_174_);
v___x_186_ = lean_alloc_ctor(1, 1, 0);
lean_ctor_set(v___x_186_, 0, v___x_185_);
v___x_187_ = ((lean_object*)(lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___closed__0));
if (v_suppressElabErrors_177_ == 0)
{
lean_del_object(v___x_182_);
v___y_106_ = v___x_187_;
v___y_107_ = v___y_171_;
v___y_108_ = v___x_186_;
v___y_109_ = v___y_173_;
v___y_110_ = v_a_180_;
v___y_111_ = v_fileName_175_;
v___y_112_ = v___x_184_;
v___y_113_ = v___y_103_;
goto v___jp_105_;
}
else
{
lean_object* v___x_188_; lean_object* v___x_189_; lean_object* v___f_190_; uint8_t v___x_191_; 
v___x_188_ = lean_box(v___y_170_);
v___x_189_ = lean_box(v_suppressElabErrors_177_);
v___f_190_ = lean_alloc_closure((void*)(lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___lam__0___boxed), 3, 2);
lean_closure_set(v___f_190_, 0, v___x_188_);
lean_closure_set(v___f_190_, 1, v___x_189_);
lean_inc(v_a_180_);
v___x_191_ = l_Lean_MessageData_hasTag(v___f_190_, v_a_180_);
if (v___x_191_ == 0)
{
lean_object* v___x_192_; lean_object* v___x_194_; 
lean_dec_ref_known(v___x_186_, 1);
lean_dec_ref(v___x_184_);
lean_dec(v_a_180_);
v___x_192_ = lean_box(0);
if (v_isShared_183_ == 0)
{
lean_ctor_set(v___x_182_, 0, v___x_192_);
v___x_194_ = v___x_182_;
goto v_reusejp_193_;
}
else
{
lean_object* v_reuseFailAlloc_195_; 
v_reuseFailAlloc_195_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v_reuseFailAlloc_195_, 0, v___x_192_);
v___x_194_ = v_reuseFailAlloc_195_;
goto v_reusejp_193_;
}
v_reusejp_193_:
{
return v___x_194_;
}
}
else
{
lean_del_object(v___x_182_);
v___y_106_ = v___x_187_;
v___y_107_ = v___y_171_;
v___y_108_ = v___x_186_;
v___y_109_ = v___y_173_;
v___y_110_ = v_a_180_;
v___y_111_ = v_fileName_175_;
v___y_112_ = v___x_184_;
v___y_113_ = v___y_103_;
goto v___jp_105_;
}
}
}
}
v___jp_197_:
{
lean_object* v___x_203_; 
v___x_203_ = l_Lean_Syntax_getTailPos_x3f(v___y_201_, v___y_200_);
lean_dec(v___y_201_);
if (lean_obj_tag(v___x_203_) == 0)
{
lean_inc(v___y_202_);
v___y_170_ = v___y_198_;
v___y_171_ = v___y_199_;
v___y_172_ = v___y_202_;
v___y_173_ = v___y_200_;
v___y_174_ = v___y_202_;
goto v___jp_169_;
}
else
{
lean_object* v_val_204_; 
v_val_204_ = lean_ctor_get(v___x_203_, 0);
lean_inc(v_val_204_);
lean_dec_ref_known(v___x_203_, 1);
v___y_170_ = v___y_198_;
v___y_171_ = v___y_199_;
v___y_172_ = v___y_202_;
v___y_173_ = v___y_200_;
v___y_174_ = v_val_204_;
goto v___jp_169_;
}
}
v___jp_205_:
{
lean_object* v___x_209_; 
v___x_209_ = l_Lean_Elab_Command_getRef___redArg(v___y_102_);
if (lean_obj_tag(v___x_209_) == 0)
{
lean_object* v_a_210_; lean_object* v_ref_211_; lean_object* v___x_212_; 
v_a_210_ = lean_ctor_get(v___x_209_, 0);
lean_inc(v_a_210_);
lean_dec_ref_known(v___x_209_, 1);
v_ref_211_ = l_Lean_replaceRef(v_ref_98_, v_a_210_);
lean_dec(v_a_210_);
v___x_212_ = l_Lean_Syntax_getPos_x3f(v_ref_211_, v___y_207_);
if (lean_obj_tag(v___x_212_) == 0)
{
lean_object* v___x_213_; 
v___x_213_ = lean_unsigned_to_nat(0u);
v___y_198_ = v___y_206_;
v___y_199_ = v___y_208_;
v___y_200_ = v___y_207_;
v___y_201_ = v_ref_211_;
v___y_202_ = v___x_213_;
goto v___jp_197_;
}
else
{
lean_object* v_val_214_; 
v_val_214_ = lean_ctor_get(v___x_212_, 0);
lean_inc(v_val_214_);
lean_dec_ref_known(v___x_212_, 1);
v___y_198_ = v___y_206_;
v___y_199_ = v___y_208_;
v___y_200_ = v___y_207_;
v___y_201_ = v_ref_211_;
v___y_202_ = v_val_214_;
goto v___jp_197_;
}
}
else
{
lean_object* v_a_215_; lean_object* v___x_217_; uint8_t v_isShared_218_; uint8_t v_isSharedCheck_222_; 
lean_dec_ref(v_msgData_99_);
v_a_215_ = lean_ctor_get(v___x_209_, 0);
v_isSharedCheck_222_ = !lean_is_exclusive(v___x_209_);
if (v_isSharedCheck_222_ == 0)
{
v___x_217_ = v___x_209_;
v_isShared_218_ = v_isSharedCheck_222_;
goto v_resetjp_216_;
}
else
{
lean_inc(v_a_215_);
lean_dec(v___x_209_);
v___x_217_ = lean_box(0);
v_isShared_218_ = v_isSharedCheck_222_;
goto v_resetjp_216_;
}
v_resetjp_216_:
{
lean_object* v___x_220_; 
if (v_isShared_218_ == 0)
{
v___x_220_ = v___x_217_;
goto v_reusejp_219_;
}
else
{
lean_object* v_reuseFailAlloc_221_; 
v_reuseFailAlloc_221_ = lean_alloc_ctor(1, 1, 0);
lean_ctor_set(v_reuseFailAlloc_221_, 0, v_a_215_);
v___x_220_ = v_reuseFailAlloc_221_;
goto v_reusejp_219_;
}
v_reusejp_219_:
{
return v___x_220_;
}
}
}
}
v___jp_224_:
{
if (v___y_227_ == 0)
{
v___y_206_ = v___y_225_;
v___y_207_ = v___y_226_;
v___y_208_ = v_severity_100_;
goto v___jp_205_;
}
else
{
v___y_206_ = v___y_225_;
v___y_207_ = v___y_226_;
v___y_208_ = v___x_223_;
goto v___jp_205_;
}
}
v___jp_228_:
{
if (v___y_229_ == 0)
{
lean_object* v___x_230_; lean_object* v_scopes_231_; lean_object* v___x_232_; lean_object* v___x_233_; lean_object* v_opts_234_; uint8_t v___x_235_; uint8_t v___x_236_; 
v___x_230_ = lean_st_ref_get(v___y_103_);
v_scopes_231_ = lean_ctor_get(v___x_230_, 2);
lean_inc(v_scopes_231_);
lean_dec(v___x_230_);
v___x_232_ = l_Lean_Elab_Command_instInhabitedScope_default;
v___x_233_ = l_List_head_x21___redArg(v___x_232_, v_scopes_231_);
lean_dec(v_scopes_231_);
v_opts_234_ = lean_ctor_get(v___x_233_, 1);
lean_inc_ref(v_opts_234_);
lean_dec(v___x_233_);
v___x_235_ = 1;
v___x_236_ = l_Lean_instBEqMessageSeverity_beq(v_severity_100_, v___x_235_);
if (v___x_236_ == 0)
{
lean_dec_ref(v_opts_234_);
v___y_225_ = v___y_229_;
v___y_226_ = v___y_229_;
v___y_227_ = v___x_236_;
goto v___jp_224_;
}
else
{
lean_object* v___x_237_; uint8_t v___x_238_; 
v___x_237_ = l_Lean_warningAsError;
v___x_238_ = lp_importGraph_Lean_Option_get___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__7(v_opts_234_, v___x_237_);
lean_dec_ref(v_opts_234_);
v___y_225_ = v___y_229_;
v___y_226_ = v___y_229_;
v___y_227_ = v___x_238_;
goto v___jp_224_;
}
}
else
{
lean_object* v___x_239_; lean_object* v___x_240_; 
lean_dec_ref(v_msgData_99_);
v___x_239_ = lean_box(0);
v___x_240_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_240_, 0, v___x_239_);
return v___x_240_;
}
}
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5___boxed(lean_object* v_ref_243_, lean_object* v_msgData_244_, lean_object* v_severity_245_, lean_object* v_isSilent_246_, lean_object* v___y_247_, lean_object* v___y_248_, lean_object* v___y_249_){
_start:
{
uint8_t v_severity_boxed_250_; uint8_t v_isSilent_boxed_251_; lean_object* v_res_252_; 
v_severity_boxed_250_ = lean_unbox(v_severity_245_);
v_isSilent_boxed_251_ = lean_unbox(v_isSilent_246_);
v_res_252_ = lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5(v_ref_243_, v_msgData_244_, v_severity_boxed_250_, v_isSilent_boxed_251_, v___y_247_, v___y_248_);
lean_dec(v___y_248_);
lean_dec_ref(v___y_247_);
lean_dec(v_ref_243_);
return v_res_252_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4(lean_object* v_msgData_253_, uint8_t v_severity_254_, uint8_t v_isSilent_255_, lean_object* v___y_256_, lean_object* v___y_257_){
_start:
{
lean_object* v___x_259_; 
v___x_259_ = l_Lean_Elab_Command_getRef___redArg(v___y_256_);
if (lean_obj_tag(v___x_259_) == 0)
{
lean_object* v_a_260_; lean_object* v___x_261_; 
v_a_260_ = lean_ctor_get(v___x_259_, 0);
lean_inc(v_a_260_);
lean_dec_ref_known(v___x_259_, 1);
v___x_261_ = lp_importGraph_Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5(v_a_260_, v_msgData_253_, v_severity_254_, v_isSilent_255_, v___y_256_, v___y_257_);
lean_dec(v_a_260_);
return v___x_261_;
}
else
{
lean_object* v_a_262_; lean_object* v___x_264_; uint8_t v_isShared_265_; uint8_t v_isSharedCheck_269_; 
lean_dec_ref(v_msgData_253_);
v_a_262_ = lean_ctor_get(v___x_259_, 0);
v_isSharedCheck_269_ = !lean_is_exclusive(v___x_259_);
if (v_isSharedCheck_269_ == 0)
{
v___x_264_ = v___x_259_;
v_isShared_265_ = v_isSharedCheck_269_;
goto v_resetjp_263_;
}
else
{
lean_inc(v_a_262_);
lean_dec(v___x_259_);
v___x_264_ = lean_box(0);
v_isShared_265_ = v_isSharedCheck_269_;
goto v_resetjp_263_;
}
v_resetjp_263_:
{
lean_object* v___x_267_; 
if (v_isShared_265_ == 0)
{
v___x_267_ = v___x_264_;
goto v_reusejp_266_;
}
else
{
lean_object* v_reuseFailAlloc_268_; 
v_reuseFailAlloc_268_ = lean_alloc_ctor(1, 1, 0);
lean_ctor_set(v_reuseFailAlloc_268_, 0, v_a_262_);
v___x_267_ = v_reuseFailAlloc_268_;
goto v_reusejp_266_;
}
v_reusejp_266_:
{
return v___x_267_;
}
}
}
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4___boxed(lean_object* v_msgData_270_, lean_object* v_severity_271_, lean_object* v_isSilent_272_, lean_object* v___y_273_, lean_object* v___y_274_, lean_object* v___y_275_){
_start:
{
uint8_t v_severity_boxed_276_; uint8_t v_isSilent_boxed_277_; lean_object* v_res_278_; 
v_severity_boxed_276_ = lean_unbox(v_severity_271_);
v_isSilent_boxed_277_ = lean_unbox(v_isSilent_272_);
v_res_278_ = lp_importGraph_Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4(v_msgData_270_, v_severity_boxed_276_, v_isSilent_boxed_277_, v___y_273_, v___y_274_);
lean_dec(v___y_274_);
lean_dec_ref(v___y_273_);
return v_res_278_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3(lean_object* v_msgData_279_, lean_object* v___y_280_, lean_object* v___y_281_){
_start:
{
uint8_t v___x_283_; uint8_t v___x_284_; lean_object* v___x_285_; 
v___x_283_ = 0;
v___x_284_ = 0;
v___x_285_ = lp_importGraph_Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4(v_msgData_279_, v___x_283_, v___x_284_, v___y_280_, v___y_281_);
return v___x_285_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3___boxed(lean_object* v_msgData_286_, lean_object* v___y_287_, lean_object* v___y_288_, lean_object* v___y_289_){
_start:
{
lean_object* v_res_290_; 
v_res_290_ = lp_importGraph_Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3(v_msgData_286_, v___y_287_, v___y_288_);
lean_dec(v___y_288_);
lean_dec_ref(v___y_287_);
return v_res_290_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_List_foldl___at___00Std_Format_joinSep___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__2_spec__2(lean_object* v_x_291_, lean_object* v_x_292_, lean_object* v_x_293_){
_start:
{
if (lean_obj_tag(v_x_293_) == 0)
{
lean_dec(v_x_291_);
return v_x_292_;
}
else
{
lean_object* v_head_294_; lean_object* v_tail_295_; lean_object* v___x_297_; uint8_t v_isShared_298_; uint8_t v_isSharedCheck_307_; 
v_head_294_ = lean_ctor_get(v_x_293_, 0);
v_tail_295_ = lean_ctor_get(v_x_293_, 1);
v_isSharedCheck_307_ = !lean_is_exclusive(v_x_293_);
if (v_isSharedCheck_307_ == 0)
{
v___x_297_ = v_x_293_;
v_isShared_298_ = v_isSharedCheck_307_;
goto v_resetjp_296_;
}
else
{
lean_inc(v_tail_295_);
lean_inc(v_head_294_);
lean_dec(v_x_293_);
v___x_297_ = lean_box(0);
v_isShared_298_ = v_isSharedCheck_307_;
goto v_resetjp_296_;
}
v_resetjp_296_:
{
lean_object* v___x_300_; 
lean_inc(v_x_291_);
if (v_isShared_298_ == 0)
{
lean_ctor_set_tag(v___x_297_, 5);
lean_ctor_set(v___x_297_, 1, v_x_291_);
lean_ctor_set(v___x_297_, 0, v_x_292_);
v___x_300_ = v___x_297_;
goto v_reusejp_299_;
}
else
{
lean_object* v_reuseFailAlloc_306_; 
v_reuseFailAlloc_306_ = lean_alloc_ctor(5, 2, 0);
lean_ctor_set(v_reuseFailAlloc_306_, 0, v_x_292_);
lean_ctor_set(v_reuseFailAlloc_306_, 1, v_x_291_);
v___x_300_ = v_reuseFailAlloc_306_;
goto v_reusejp_299_;
}
v_reusejp_299_:
{
uint8_t v___x_301_; lean_object* v___x_302_; lean_object* v___x_303_; lean_object* v___x_304_; 
v___x_301_ = 1;
v___x_302_ = l_Lean_Name_toString(v_head_294_, v___x_301_);
v___x_303_ = lean_alloc_ctor(3, 1, 0);
lean_ctor_set(v___x_303_, 0, v___x_302_);
v___x_304_ = lean_alloc_ctor(5, 2, 0);
lean_ctor_set(v___x_304_, 0, v___x_300_);
lean_ctor_set(v___x_304_, 1, v___x_303_);
v_x_292_ = v___x_304_;
v_x_293_ = v_tail_295_;
goto _start;
}
}
}
}
}
LEAN_EXPORT lean_object* lp_importGraph_Std_Format_joinSep___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__2(lean_object* v_x_308_, lean_object* v_x_309_){
_start:
{
if (lean_obj_tag(v_x_308_) == 0)
{
lean_object* v___x_310_; 
lean_dec(v_x_309_);
v___x_310_ = lean_box(0);
return v___x_310_;
}
else
{
lean_object* v_tail_311_; 
v_tail_311_ = lean_ctor_get(v_x_308_, 1);
if (lean_obj_tag(v_tail_311_) == 0)
{
lean_object* v_head_312_; uint8_t v___x_313_; lean_object* v___x_314_; lean_object* v___x_315_; 
lean_dec(v_x_309_);
v_head_312_ = lean_ctor_get(v_x_308_, 0);
lean_inc(v_head_312_);
lean_dec_ref_known(v_x_308_, 2);
v___x_313_ = 1;
v___x_314_ = l_Lean_Name_toString(v_head_312_, v___x_313_);
v___x_315_ = lean_alloc_ctor(3, 1, 0);
lean_ctor_set(v___x_315_, 0, v___x_314_);
return v___x_315_;
}
else
{
lean_object* v_head_316_; uint8_t v___x_317_; lean_object* v___x_318_; lean_object* v___x_319_; lean_object* v___x_320_; 
lean_inc(v_tail_311_);
v_head_316_ = lean_ctor_get(v_x_308_, 0);
lean_inc(v_head_316_);
lean_dec_ref_known(v_x_308_, 2);
v___x_317_ = 1;
v___x_318_ = l_Lean_Name_toString(v_head_316_, v___x_317_);
v___x_319_ = lean_alloc_ctor(3, 1, 0);
lean_ctor_set(v___x_319_, 0, v___x_318_);
v___x_320_ = lp_importGraph_List_foldl___at___00Std_Format_joinSep___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__2_spec__2(v_x_309_, v___x_319_, v_tail_311_);
return v___x_320_;
}
}
}
}
LEAN_EXPORT lean_object* lp_importGraph_Std_DTreeMap_Internal_Impl_foldrM___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__1(lean_object* v_init_321_, lean_object* v_x_322_){
_start:
{
if (lean_obj_tag(v_x_322_) == 0)
{
lean_object* v_k_323_; lean_object* v_l_324_; lean_object* v_r_325_; lean_object* v___x_326_; lean_object* v___x_327_; 
v_k_323_ = lean_ctor_get(v_x_322_, 1);
v_l_324_ = lean_ctor_get(v_x_322_, 3);
v_r_325_ = lean_ctor_get(v_x_322_, 4);
v___x_326_ = lp_importGraph_Std_DTreeMap_Internal_Impl_foldrM___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__1(v_init_321_, v_r_325_);
lean_inc(v_k_323_);
v___x_327_ = lean_alloc_ctor(1, 2, 0);
lean_ctor_set(v___x_327_, 0, v_k_323_);
lean_ctor_set(v___x_327_, 1, v___x_326_);
v_init_321_ = v___x_327_;
v_x_322_ = v_l_324_;
goto _start;
}
else
{
return v_init_321_;
}
}
}
LEAN_EXPORT lean_object* lp_importGraph_Std_DTreeMap_Internal_Impl_foldrM___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__1___boxed(lean_object* v_init_329_, lean_object* v_x_330_){
_start:
{
lean_object* v_res_331_; 
v_res_331_ = lp_importGraph_Std_DTreeMap_Internal_Impl_foldrM___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__1(v_init_329_, v_x_330_);
lean_dec(v_x_330_);
return v_res_331_;
}
}
static lean_object* _init_lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__3(void){
_start:
{
lean_object* v___x_337_; lean_object* v___x_338_; 
v___x_337_ = ((lean_object*)(lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__2));
v___x_338_ = l_Lean_MessageData_ofFormat(v___x_337_);
return v___x_338_;
}
}
static lean_object* _init_lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__8(void){
_start:
{
lean_object* v___x_345_; lean_object* v___x_346_; 
v___x_345_ = ((lean_object*)(lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__7));
v___x_346_ = l_Lean_MessageData_ofFormat(v___x_345_);
return v___x_346_;
}
}
LEAN_EXPORT lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1(lean_object* v_x_347_, lean_object* v_a_348_, lean_object* v_a_349_){
_start:
{
lean_object* v___x_351_; uint8_t v___x_352_; 
v___x_351_ = ((lean_object*)(lp_importGraph_command_x23redundant__imports___closed__1));
v___x_352_ = l_Lean_Syntax_isOfKind(v_x_347_, v___x_351_);
if (v___x_352_ == 0)
{
lean_object* v___x_353_; 
v___x_353_ = lp_importGraph_Lean_Elab_throwUnsupportedSyntax___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__0___redArg();
return v___x_353_;
}
else
{
lean_object* v___x_354_; lean_object* v___x_355_; 
v___x_354_ = ((lean_object*)(lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__0));
v___x_355_ = l_Lean_Elab_Command_liftCoreM___redArg(v___x_354_, v_a_348_, v_a_349_);
if (lean_obj_tag(v___x_355_) == 0)
{
lean_object* v_a_356_; 
v_a_356_ = lean_ctor_get(v___x_355_, 0);
lean_inc(v_a_356_);
lean_dec_ref_known(v___x_355_, 1);
if (lean_obj_tag(v_a_356_) == 0)
{
goto v___jp_357_;
}
else
{
if (v___x_352_ == 0)
{
goto v___jp_357_;
}
else
{
lean_object* v___x_366_; lean_object* v___x_367_; 
v___x_366_ = lean_obj_once(&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__8, &lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__8_once, _init_lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__8);
v___x_367_ = lp_importGraph_Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3(v___x_366_, v_a_348_, v_a_349_);
return v___x_367_;
}
}
v___jp_357_:
{
lean_object* v___x_358_; lean_object* v___x_359_; lean_object* v___x_360_; lean_object* v___x_361_; lean_object* v___x_362_; lean_object* v___x_363_; lean_object* v___x_364_; lean_object* v___x_365_; 
v___x_358_ = lean_obj_once(&lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__3, &lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__3_once, _init_lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__3);
v___x_359_ = lean_box(0);
v___x_360_ = lp_importGraph_Std_DTreeMap_Internal_Impl_foldrM___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__1(v___x_359_, v_a_356_);
lean_dec(v_a_356_);
v___x_361_ = ((lean_object*)(lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___closed__5));
v___x_362_ = lp_importGraph_Std_Format_joinSep___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__2(v___x_360_, v___x_361_);
v___x_363_ = l_Lean_MessageData_ofFormat(v___x_362_);
v___x_364_ = lean_alloc_ctor(7, 2, 0);
lean_ctor_set(v___x_364_, 0, v___x_358_);
lean_ctor_set(v___x_364_, 1, v___x_363_);
v___x_365_ = lp_importGraph_Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3(v___x_364_, v_a_348_, v_a_349_);
return v___x_365_;
}
}
else
{
lean_object* v_a_368_; lean_object* v___x_370_; uint8_t v_isShared_371_; uint8_t v_isSharedCheck_375_; 
v_a_368_ = lean_ctor_get(v___x_355_, 0);
v_isSharedCheck_375_ = !lean_is_exclusive(v___x_355_);
if (v_isSharedCheck_375_ == 0)
{
v___x_370_ = v___x_355_;
v_isShared_371_ = v_isSharedCheck_375_;
goto v_resetjp_369_;
}
else
{
lean_inc(v_a_368_);
lean_dec(v___x_355_);
v___x_370_ = lean_box(0);
v_isShared_371_ = v_isSharedCheck_375_;
goto v_resetjp_369_;
}
v_resetjp_369_:
{
lean_object* v___x_373_; 
if (v_isShared_371_ == 0)
{
v___x_373_ = v___x_370_;
goto v_reusejp_372_;
}
else
{
lean_object* v_reuseFailAlloc_374_; 
v_reuseFailAlloc_374_ = lean_alloc_ctor(1, 1, 0);
lean_ctor_set(v_reuseFailAlloc_374_, 0, v_a_368_);
v___x_373_ = v_reuseFailAlloc_374_;
goto v_reusejp_372_;
}
v_reusejp_372_:
{
return v___x_373_;
}
}
}
}
}
}
LEAN_EXPORT lean_object* lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1___boxed(lean_object* v_x_376_, lean_object* v_a_377_, lean_object* v_a_378_, lean_object* v_a_379_){
_start:
{
lean_object* v_res_380_; 
v_res_380_ = lp_importGraph___aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1(v_x_376_, v_a_377_, v_a_378_);
lean_dec(v_a_378_);
lean_dec_ref(v_a_377_);
return v_res_380_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6(lean_object* v_msgData_381_, lean_object* v___y_382_, lean_object* v___y_383_){
_start:
{
lean_object* v___x_385_; 
v___x_385_ = lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___redArg(v_msgData_381_, v___y_383_);
return v___x_385_;
}
}
LEAN_EXPORT lean_object* lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6___boxed(lean_object* v_msgData_386_, lean_object* v___y_387_, lean_object* v___y_388_, lean_object* v___y_389_){
_start:
{
lean_object* v_res_390_; 
v_res_390_ = lp_importGraph_Lean_addMessageContextPartial___at___00Lean_logAt___at___00Lean_log___at___00Lean_logInfo___at___00__aux__ImportGraph__Tools__RedundantImports______elabRules__command_x23redundant__imports__1_spec__3_spec__4_spec__5_spec__6(v_msgData_386_, v___y_387_, v___y_388_);
lean_dec(v___y_388_);
lean_dec_ref(v___y_387_);
return v_res_390_;
}
}
lean_object* runtime_initialize_Init(uint8_t builtin);
void lean_initialize_runtime_module();
static bool _G_runtime_initialized = false;
LEAN_EXPORT lean_object* runtime_initialize_importGraph_ImportGraph_Tools_RedundantImports(uint8_t builtin) {
lean_object * res;
if (_G_runtime_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_runtime_initialized = true;
lean_initialize_runtime_module();
res = runtime_initialize_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return lean_io_result_mk_ok(lean_box(0));
}
lean_object* runtime_initialize_Init(uint8_t builtin);
lean_object* runtime_initialize_Lean_Elab_Command(uint8_t builtin);
lean_object* runtime_initialize_Lean_Widget_UserWidget(uint8_t builtin);
lean_object* runtime_initialize_importGraph_ImportGraph_Imports_Redundant(uint8_t builtin);
static bool _G_meta_initialized = false;
LEAN_EXPORT lean_object* meta_initialize_importGraph_ImportGraph_Tools_RedundantImports(uint8_t builtin) {
lean_object * res;
if (_G_meta_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_meta_initialized = true;
res = runtime_initialize_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_Lean_Elab_Command(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_Lean_Widget_UserWidget(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_importGraph_ImportGraph_Imports_Redundant(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return lean_io_result_mk_ok(lean_box(0));
}
lean_object* initialize_Init(uint8_t builtin);
lean_object* initialize_Init(uint8_t builtin);
lean_object* initialize_Lean_Elab_Command(uint8_t builtin);
lean_object* initialize_Lean_Widget_UserWidget(uint8_t builtin);
lean_object* initialize_importGraph_ImportGraph_Imports_Redundant(uint8_t builtin);
static bool _G_initialized = false;
LEAN_EXPORT lean_object* initialize_importGraph_ImportGraph_Tools_RedundantImports(uint8_t builtin) {
lean_object * res;
if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_initialized = true;
res = initialize_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Elab_Command(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Lean_Widget_UserWidget(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_importGraph_ImportGraph_Imports_Redundant(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_importGraph_ImportGraph_Tools_RedundantImports(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = meta_initialize_importGraph_ImportGraph_Tools_RedundantImports(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return initialize_importGraph_ImportGraph_Tools_RedundantImports(builtin);
}
#ifdef __cplusplus
}
#endif
