// Lean compiler output
// Module: Mathlib.Tactic.SetLike
// Imports: public import Init public meta import Init public import Aesop.Frontend public meta import Batteries.Util.LibraryNote public import Mathlib.Init public import Aesop.Frontend.Basic public import Batteries.Util.LibraryNote
#include <lean/lean.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined(__GNUC__) && !defined(__CLANG__)
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#endif
#ifdef __cplusplus
extern "C" {
#endif
lean_object* l_Lean_Name_mkStr1(lean_object*);
lean_object* l_Array_mkArray1___redArg(lean_object*);
lean_object* lean_array_get_size(lean_object*);
uint8_t lean_nat_dec_lt(lean_object*, lean_object*);
uint8_t lean_nat_dec_le(lean_object*, lean_object*);
size_t lean_usize_of_nat(lean_object*);
uint8_t lean_usize_dec_eq(size_t, size_t);
lean_object* lean_array_uget_borrowed(lean_object*, size_t);
lean_object* lp_aesop_Aesop_Frontend_declareRuleSetUnchecked(lean_object*, uint8_t);
size_t lean_usize_add(size_t, size_t);
LEAN_EXPORT lean_object* lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__spec__0(lean_object*, size_t, size_t, lean_object*);
LEAN_EXPORT lean_object* lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__spec__0___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
static const lean_string_object lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__0_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 8, .m_capacity = 8, .m_length = 7, .m_data = "SetLike"};
static const lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__0_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_ = (const lean_object*)&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__0_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__value;
static const lean_ctor_object lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__1_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_ctor_object) + sizeof(void*)*2 + 8, .m_other = 2, .m_tag = 1}, .m_objs = {((lean_object*)(((size_t)(0) << 1) | 1)),((lean_object*)&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__0_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__value),LEAN_SCALAR_PTR_LITERAL(146, 248, 10, 158, 176, 176, 178, 2)}};
static const lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__1_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_ = (const lean_object*)&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__1_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__value;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static uint8_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static uint8_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static size_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_;
LEAN_EXPORT lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_();
LEAN_EXPORT lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3____boxed(lean_object*);
LEAN_EXPORT lean_object* lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__spec__0(lean_object*, size_t, size_t, lean_object*);
LEAN_EXPORT lean_object* lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__spec__0___boxed(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
static const lean_string_object lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__0_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__value = {.m_header = {.m_rc = 0, .m_cs_sz = 0, .m_other = 0, .m_tag = 249}, .m_size = 9, .m_capacity = 9, .m_length = 8, .m_data = "SetLike!"};
static const lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__0_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_ = (const lean_object*)&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__0_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__value;
static const lean_ctor_object lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__1_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__value = {.m_header = {.m_rc = 0, .m_cs_sz = sizeof(lean_ctor_object) + sizeof(void*)*2 + 8, .m_other = 2, .m_tag = 1}, .m_objs = {((lean_object*)(((size_t)(0) << 1) | 1)),((lean_object*)&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__0_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__value),LEAN_SCALAR_PTR_LITERAL(166, 196, 79, 182, 131, 43, 55, 65)}};
static const lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__1_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_ = (const lean_object*)&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__1_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__value;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static uint8_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static uint8_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_;
static lean_once_cell_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once = LEAN_ONCE_CELL_INITIALIZER;
static size_t lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_;
LEAN_EXPORT lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_();
LEAN_EXPORT lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3____boxed(lean_object*);
LEAN_EXPORT lean_object* lp_mathlib_LibraryNote_SetLike__Aesop__ruleset;
LEAN_EXPORT lean_object* lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__spec__0(lean_object* v_as_1_, size_t v_i_2_, size_t v_stop_3_, lean_object* v_b_4_){
_start:
{
uint8_t v___x_6_; 
v___x_6_ = lean_usize_dec_eq(v_i_2_, v_stop_3_);
if (v___x_6_ == 0)
{
lean_object* v___x_7_; uint8_t v___x_8_; lean_object* v___x_9_; 
v___x_7_ = lean_array_uget_borrowed(v_as_1_, v_i_2_);
v___x_8_ = 1;
lean_inc(v___x_7_);
v___x_9_ = lp_aesop_Aesop_Frontend_declareRuleSetUnchecked(v___x_7_, v___x_8_);
if (lean_obj_tag(v___x_9_) == 0)
{
lean_object* v_a_10_; size_t v___x_11_; size_t v___x_12_; 
v_a_10_ = lean_ctor_get(v___x_9_, 0);
lean_inc(v_a_10_);
lean_dec_ref_known(v___x_9_, 1);
v___x_11_ = ((size_t)1ULL);
v___x_12_ = lean_usize_add(v_i_2_, v___x_11_);
v_i_2_ = v___x_12_;
v_b_4_ = v_a_10_;
goto _start;
}
else
{
return v___x_9_;
}
}
else
{
lean_object* v___x_14_; 
v___x_14_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_14_, 0, v_b_4_);
return v___x_14_;
}
}
}
LEAN_EXPORT lean_object* lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__spec__0___boxed(lean_object* v_as_15_, lean_object* v_i_16_, lean_object* v_stop_17_, lean_object* v_b_18_, lean_object* v___y_19_){
_start:
{
size_t v_i_boxed_20_; size_t v_stop_boxed_21_; lean_object* v_res_22_; 
v_i_boxed_20_ = lean_unbox_usize(v_i_16_);
lean_dec(v_i_16_);
v_stop_boxed_21_ = lean_unbox_usize(v_stop_17_);
lean_dec(v_stop_17_);
v_res_22_ = lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__spec__0(v_as_15_, v_i_boxed_20_, v_stop_boxed_21_, v_b_18_);
lean_dec_ref(v_as_15_);
return v_res_22_;
}
}
static lean_object* _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_26_; lean_object* v___x_27_; 
v___x_26_ = ((lean_object*)(lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__1_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_));
v___x_27_ = l_Array_mkArray1___redArg(v___x_26_);
return v___x_27_;
}
}
static lean_object* _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_28_; lean_object* v___x_29_; 
v___x_28_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
v___x_29_ = lean_array_get_size(v___x_28_);
return v___x_29_;
}
}
static uint8_t _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_30_; lean_object* v___x_31_; uint8_t v___x_32_; 
v___x_30_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
v___x_31_ = lean_unsigned_to_nat(0u);
v___x_32_ = lean_nat_dec_lt(v___x_31_, v___x_30_);
return v___x_32_;
}
}
static uint8_t _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_33_; uint8_t v___x_34_; 
v___x_33_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
v___x_34_ = lean_nat_dec_le(v___x_33_, v___x_33_);
return v___x_34_;
}
}
static size_t _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_35_; size_t v___x_36_; 
v___x_35_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
v___x_36_ = lean_usize_of_nat(v___x_35_);
return v___x_36_;
}
}
LEAN_EXPORT lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_(){
_start:
{
lean_object* v___x_38_; lean_object* v___x_39_; uint8_t v___x_40_; 
v___x_38_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
v___x_39_ = lean_box(0);
v___x_40_ = lean_uint8_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
if (v___x_40_ == 0)
{
lean_object* v___x_41_; 
v___x_41_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_41_, 0, v___x_39_);
return v___x_41_;
}
else
{
uint8_t v___x_42_; 
v___x_42_ = lean_uint8_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
if (v___x_42_ == 0)
{
if (v___x_40_ == 0)
{
lean_object* v___x_43_; 
v___x_43_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_43_, 0, v___x_39_);
return v___x_43_;
}
else
{
size_t v___x_44_; size_t v___x_45_; lean_object* v___x_46_; 
v___x_44_ = ((size_t)0ULL);
v___x_45_ = lean_usize_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
v___x_46_ = lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__spec__0(v___x_38_, v___x_44_, v___x_45_, v___x_39_);
return v___x_46_;
}
}
else
{
size_t v___x_47_; size_t v___x_48_; lean_object* v___x_49_; 
v___x_47_ = ((size_t)0ULL);
v___x_48_ = lean_usize_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_);
v___x_49_ = lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3__spec__0(v___x_38_, v___x_47_, v___x_48_, v___x_39_);
return v___x_49_;
}
}
}
}
LEAN_EXPORT lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3____boxed(lean_object* v_a_50_){
_start:
{
lean_object* v_res_51_; 
v_res_51_ = lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_();
return v_res_51_;
}
}
LEAN_EXPORT lean_object* lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__spec__0(lean_object* v_as_52_, size_t v_i_53_, size_t v_stop_54_, lean_object* v_b_55_){
_start:
{
uint8_t v___x_57_; 
v___x_57_ = lean_usize_dec_eq(v_i_53_, v_stop_54_);
if (v___x_57_ == 0)
{
lean_object* v___x_58_; lean_object* v___x_59_; 
v___x_58_ = lean_array_uget_borrowed(v_as_52_, v_i_53_);
lean_inc(v___x_58_);
v___x_59_ = lp_aesop_Aesop_Frontend_declareRuleSetUnchecked(v___x_58_, v___x_57_);
if (lean_obj_tag(v___x_59_) == 0)
{
lean_object* v_a_60_; size_t v___x_61_; size_t v___x_62_; 
v_a_60_ = lean_ctor_get(v___x_59_, 0);
lean_inc(v_a_60_);
lean_dec_ref_known(v___x_59_, 1);
v___x_61_ = ((size_t)1ULL);
v___x_62_ = lean_usize_add(v_i_53_, v___x_61_);
v_i_53_ = v___x_62_;
v_b_55_ = v_a_60_;
goto _start;
}
else
{
return v___x_59_;
}
}
else
{
lean_object* v___x_64_; 
v___x_64_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_64_, 0, v_b_55_);
return v___x_64_;
}
}
}
LEAN_EXPORT lean_object* lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__spec__0___boxed(lean_object* v_as_65_, lean_object* v_i_66_, lean_object* v_stop_67_, lean_object* v_b_68_, lean_object* v___y_69_){
_start:
{
size_t v_i_boxed_70_; size_t v_stop_boxed_71_; lean_object* v_res_72_; 
v_i_boxed_70_ = lean_unbox_usize(v_i_66_);
lean_dec(v_i_66_);
v_stop_boxed_71_ = lean_unbox_usize(v_stop_67_);
lean_dec(v_stop_67_);
v_res_72_ = lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__spec__0(v_as_65_, v_i_boxed_70_, v_stop_boxed_71_, v_b_68_);
lean_dec_ref(v_as_65_);
return v_res_72_;
}
}
static lean_object* _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_76_; lean_object* v___x_77_; 
v___x_76_ = ((lean_object*)(lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__1_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_));
v___x_77_ = l_Array_mkArray1___redArg(v___x_76_);
return v___x_77_;
}
}
static lean_object* _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_78_; lean_object* v___x_79_; 
v___x_78_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
v___x_79_ = lean_array_get_size(v___x_78_);
return v___x_79_;
}
}
static uint8_t _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_80_; lean_object* v___x_81_; uint8_t v___x_82_; 
v___x_80_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
v___x_81_ = lean_unsigned_to_nat(0u);
v___x_82_ = lean_nat_dec_lt(v___x_81_, v___x_80_);
return v___x_82_;
}
}
static uint8_t _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_83_; uint8_t v___x_84_; 
v___x_83_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
v___x_84_ = lean_nat_dec_le(v___x_83_, v___x_83_);
return v___x_84_;
}
}
static size_t _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_(void){
_start:
{
lean_object* v___x_85_; size_t v___x_86_; 
v___x_85_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__3_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
v___x_86_ = lean_usize_of_nat(v___x_85_);
return v___x_86_;
}
}
LEAN_EXPORT lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_(){
_start:
{
lean_object* v___x_88_; lean_object* v___x_89_; uint8_t v___x_90_; 
v___x_88_ = lean_obj_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__2_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
v___x_89_ = lean_box(0);
v___x_90_ = lean_uint8_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__4_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
if (v___x_90_ == 0)
{
lean_object* v___x_91_; 
v___x_91_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_91_, 0, v___x_89_);
return v___x_91_;
}
else
{
uint8_t v___x_92_; 
v___x_92_ = lean_uint8_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__5_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
if (v___x_92_ == 0)
{
if (v___x_90_ == 0)
{
lean_object* v___x_93_; 
v___x_93_ = lean_alloc_ctor(0, 1, 0);
lean_ctor_set(v___x_93_, 0, v___x_89_);
return v___x_93_;
}
else
{
size_t v___x_94_; size_t v___x_95_; lean_object* v___x_96_; 
v___x_94_ = ((size_t)0ULL);
v___x_95_ = lean_usize_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
v___x_96_ = lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__spec__0(v___x_88_, v___x_94_, v___x_95_, v___x_89_);
return v___x_96_;
}
}
else
{
size_t v___x_97_; size_t v___x_98_; lean_object* v___x_99_; 
v___x_97_ = ((size_t)0ULL);
v___x_98_ = lean_usize_once(&lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_, &lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__once, _init_lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn___closed__6_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_);
v___x_99_ = lp_mathlib___private_Init_Data_Array_Basic_0__Array_foldlMUnsafe_fold___at___00__private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3__spec__0(v___x_88_, v___x_97_, v___x_98_, v___x_89_);
return v___x_99_;
}
}
}
}
LEAN_EXPORT lean_object* lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3____boxed(lean_object* v_a_100_){
_start:
{
lean_object* v_res_101_; 
v_res_101_ = lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_();
return v_res_101_;
}
}
static lean_object* _init_lp_mathlib_LibraryNote_SetLike__Aesop__ruleset(void){
_start:
{
lean_object* v___x_102_; 
v___x_102_ = lean_box(0);
return v___x_102_;
}
}
lean_object* runtime_initialize_Init(uint8_t builtin);
lean_object* runtime_initialize_aesop_Aesop_Frontend(uint8_t builtin);
lean_object* runtime_initialize_mathlib_Mathlib_Init(uint8_t builtin);
lean_object* runtime_initialize_aesop_Aesop_Frontend_Basic(uint8_t builtin);
lean_object* runtime_initialize_batteries_Batteries_Util_LibraryNote(uint8_t builtin);
void lean_initialize();
static bool _G_runtime_initialized = false;
LEAN_EXPORT lean_object* runtime_initialize_mathlib_Mathlib_Tactic_SetLike(uint8_t builtin) {
lean_object * res;
if (_G_runtime_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_runtime_initialized = true;
lean_initialize();
res = runtime_initialize_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_aesop_Aesop_Frontend(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_mathlib_Mathlib_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_aesop_Aesop_Frontend_Basic(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_batteries_Batteries_Util_LibraryNote(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return lean_io_result_mk_ok(lean_box(0));
}
lean_object* runtime_initialize_Init(uint8_t builtin);
lean_object* runtime_initialize_batteries_Batteries_Util_LibraryNote(uint8_t builtin);
static bool _G_meta_initialized = false;
LEAN_EXPORT lean_object* meta_initialize_mathlib_Mathlib_Tactic_SetLike(uint8_t builtin) {
lean_object * res;
if (_G_meta_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_meta_initialized = true;
res = runtime_initialize_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_batteries_Batteries_Util_LibraryNote(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_3544750014____hygCtx___hyg_3_();
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = lp_mathlib___private_Mathlib_Tactic_SetLike_0__initFn_00___x40_Mathlib_Tactic_SetLike_2158599001____hygCtx___hyg_3_();
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
lp_mathlib_LibraryNote_SetLike__Aesop__ruleset = _init_lp_mathlib_LibraryNote_SetLike__Aesop__ruleset();
lean_mark_persistent(lp_mathlib_LibraryNote_SetLike__Aesop__ruleset);
return lean_io_result_mk_ok(lean_box(0));
}
lean_object* initialize_Init(uint8_t builtin);
lean_object* initialize_Init(uint8_t builtin);
lean_object* initialize_aesop_Aesop_Frontend(uint8_t builtin);
lean_object* initialize_batteries_Batteries_Util_LibraryNote(uint8_t builtin);
lean_object* initialize_mathlib_Mathlib_Init(uint8_t builtin);
lean_object* initialize_aesop_Aesop_Frontend_Basic(uint8_t builtin);
lean_object* initialize_batteries_Batteries_Util_LibraryNote(uint8_t builtin);
static bool _G_initialized = false;
LEAN_EXPORT lean_object* initialize_mathlib_Mathlib_Tactic_SetLike(uint8_t builtin) {
lean_object * res;
if (_G_initialized) return lean_io_result_mk_ok(lean_box(0));
_G_initialized = true;
res = initialize_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_aesop_Aesop_Frontend(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_batteries_Batteries_Util_LibraryNote(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_mathlib_Mathlib_Init(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_aesop_Aesop_Frontend_Basic(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = initialize_batteries_Batteries_Util_LibraryNote(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = runtime_initialize_mathlib_Mathlib_Tactic_SetLike(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
res = meta_initialize_mathlib_Mathlib_Tactic_SetLike(builtin);
if (lean_io_result_is_error(res)) return res;
lean_dec_ref(res);
return initialize_mathlib_Mathlib_Tactic_SetLike(builtin);
}
#ifdef __cplusplus
}
#endif
