use std::result::Result;

use super::*;

use openvm_algebra_circuit::{ModularExtension, ModularExtensionExecutor};
use openvm_circuit::{
    arch::{InitFileGenerator, SystemConfig},
    system::SystemExecutor,
};
use openvm_circuit_derive::VmConfig;
use openvm_rv32im_circuit::{Rv32I, Rv32IExecutor, Rv32Io, Rv32IoExecutor, Rv32M, Rv32MExecutor};
use openvm_stark_backend::{
    config::{StarkGenericConfig, Val},
    p3_field::Field,
    prover::hal::ProverBackend,
};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, VmConfig, Serialize, Deserialize)]
pub struct Rv32WeierstrassConfig {
    #[config(executor = SystemExecutor)]
    pub system: SystemConfig,
    #[extension(generics = false)]
    pub base: Rv32I,
    #[extension(generics = false)]
    pub mul: Rv32M,
    #[extension(generics = false)]
    pub io: Rv32Io,
    #[extension(generics = false)]
    pub modular: ModularExtension,
    #[extension(generics = false)]
    pub weierstrass: WeierstrassExtension,
}

impl Rv32WeierstrassConfig {
    pub fn new(curves: Vec<CurveConfig>) -> Self {
        let primes: Vec<_> = curves
            .iter()
            .flat_map(|c| [c.modulus.clone(), c.scalar.clone()])
            .collect();
        Self {
            system: SystemConfig::default().with_continuations(),
            base: Default::default(),
            mul: Default::default(),
            io: Default::default(),
            modular: ModularExtension::new(primes),
            weierstrass: WeierstrassExtension::new(curves),
        }
    }
}

impl InitFileGenerator for Rv32WeierstrassConfig {
    fn generate_init_file_contents(&self) -> Option<String> {
        Some(format!(
            "// This file is automatically generated by cargo openvm. Do not rename or edit.\n{}\n{}\n",
            self.modular.generate_moduli_init(),
            self.weierstrass.generate_sw_init()
        ))
    }
}
