[package]
name = "openvm-caci"
description = "OpenVM implementation of the eth-act zkVM Cryptographic Accelerators C Interface"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
openvm-keccak256 = { path = "../keccak256", default-features = false }
openvm-sha2 = { path = "../sha2", default-features = false }

[dev-dependencies]
eyre = { workspace = true }
openvm-circuit = { workspace = true, features = ["test-utils", "parallel"] }
openvm-instructions = { path = "../../crates/toolchain/instructions", default-features = false }
openvm-keccak256-circuit = { workspace = true }
openvm-keccak256-transpiler = { workspace = true }
openvm-riscv-transpiler = { workspace = true }
openvm-sdk = { path = "../../crates/sdk", default-features = false }
openvm-sha2-circuit = { workspace = true }
openvm-sha2-transpiler = { workspace = true }
openvm-stark-sdk = { workspace = true }
openvm-toolchain-tests = { workspace = true }
openvm-transpiler = { workspace = true }
sha2 = { workspace = true }
tiny-keccak = { workspace = true }

[features]
default = []
# Internal feature for testing only.
cuda = ["openvm-keccak256-circuit/cuda", "openvm-sha2-circuit/cuda"]

[lints]
workspace = true
