use std::{
    alloc::{alloc, dealloc, handle_alloc_error, Layout},
    borrow::{Borrow, BorrowMut},
    ptr::NonNull,
};

use itertools::Itertools;
use openvm_circuit_primitives_derive::AlignedBytesBorrow;
use openvm_instructions::{
    exe::{SparseMemoryImage, VmExe},
    instruction::Instruction,
    program::{Program, DEFAULT_PC_STEP},
    LocalOpcode, SystemOpcode,
};
#[cfg(test)]
use openvm_instructions::{instruction::InstructionOperand, program::MAX_ALLOWED_PC};
use openvm_stark_backend::p3_field::PrimeField32;

#[cfg(test)]
use crate::arch::execution_mode::ExecutionCtx;
#[cfg(feature = "tco")]
use crate::arch::Handler;
use crate::{
    arch::{
        execution_mode::{ExecutionCtxTrait, MeteredExecutionCtxTrait},
        ExecuteFunc, ExecutionError, Executor, ExecutorInventory, ExitCode, MeteredExecutor,
        StaticProgramError, Streams, SystemConfig, VmExecState, VmState,
    },
    system::memory::online::GuestMemory,
};

/// Precomputed interpreter for pure, metered, or preflight execution.
///
/// The execution context and constructor select the mode. The interpreter owns no VM state, so it
/// can execute multiple inputs or segments.
// NOTE: the lifetime 'a represents the lifetime of borrowed ExecutorInventory, which must outlive
// the InterpretedInstance because `pre_compute_buf` may contain pointers to references held by
// executors.
pub struct InterpretedInstance<'a, Ctx> {
    system_config: &'a SystemConfig,
    // SAFETY: this is not actually dead code, but `pre_compute_insns` contains raw pointer refers
    // to this buffer.
    #[allow(dead_code)]
    pre_compute_buf: AlignedBuf,
    /// Instruction table of function pointers and pointers to the pre-computed buffer. Indexed by
    /// the instruction slot `(pc - pc_base) / DEFAULT_PC_STEP`.
    #[cfg(not(feature = "tco"))]
    pre_compute_insns: Vec<PreComputeInstruction<Ctx>>,
    #[cfg(feature = "tco")]
    pre_compute_max_size: usize,
    /// Handler function pointers for tail call optimization.
    #[cfg(feature = "tco")]
    handlers: Vec<Handler<Ctx>>,

    pc_base: u32,
    pc_start: u32,

    init_memory: SparseMemoryImage,
}

#[repr(C)]
#[cfg_attr(feature = "tco", allow(dead_code))]
pub(crate) struct PreComputeInstruction<Ctx> {
    pub(crate) handler: ExecuteFunc<Ctx>,
    pub(crate) pre_compute: *const u8,
}

unsafe impl<Ctx> Send for PreComputeInstruction<Ctx> {}
unsafe impl<Ctx> Sync for PreComputeInstruction<Ctx> {}

#[derive(AlignedBytesBorrow, Clone)]
#[repr(C)]
struct TerminatePreCompute {
    exit_code: u32,
}

macro_rules! run {
    ($span:literal, $interpreter:ident, $exec_state:ident, $ctx:ident) => {{
        tracing::info_span!($span).in_scope(|| -> Result<(), ExecutionError> {
            // SAFETY:
            // - it is the responsibility of each Executor to ensure that pre_compute_insts contains
            //   valid function pointers and pre-computed data
            #[cfg(not(feature = "tco"))]
            {
                unsafe {
                    $crate::arch::interpreter::execute_trampoline(
                        &mut $exec_state,
                        &$interpreter.pre_compute_insns,
                        $interpreter.pc_base,
                    );
                }
            }
            #[cfg(feature = "tco")]
            {
                if <$ctx as $crate::arch::ExecutionCtxTrait>::should_suspend(&mut $exec_state) {
                    return Ok(());
                }

                let pc = $exec_state.pc();
                <$ctx as $crate::arch::ExecutionCtxTrait>::on_instruction_start(
                    &mut $exec_state,
                    pc,
                );
                let handler = $interpreter
                    .get_handler(pc)
                    .ok_or(ExecutionError::PcOutOfBounds(pc))?;
                // SAFETY:
                // - handler is generated by Executor, MeteredExecutor traits
                // - it is the responsibility of each Executor to ensure handler is safe given a
                //   valid VM state
                unsafe {
                    handler($interpreter, &mut $exec_state);
                }
            }
            Ok(())
        })?;
    }};
}

mod metered;
mod preflight;
mod pure;

pub use preflight::PreflightInterpretedInstance;

// Constructors for pure and metered execution, which generate pre-computed buffers and function
// pointers
// - Generic in `Ctx`

impl<'a, Ctx> InterpretedInstance<'a, Ctx>
where
    Ctx: ExecutionCtxTrait,
{
    /// Creates an interpreter for pure or preflight execution.
    pub fn new<F, E>(
        inventory: &'a ExecutorInventory<E>,
        exe: &VmExe,
    ) -> Result<Self, StaticProgramError>
    where
        F: PrimeField32,
        E: Executor<F>,
    {
        let program = &exe.program;
        let pre_compute_max_size = get_pre_compute_max_size::<F, _>(program, inventory);
        let mut pre_compute_buf = alloc_pre_compute_buf(program, pre_compute_max_size);
        let mut split_pre_compute_buf =
            split_pre_compute_buf(program, &mut pre_compute_buf, pre_compute_max_size);
        #[cfg(not(feature = "tco"))]
        let pre_compute_insns = get_pre_compute_instructions::<F, Ctx, E>(
            program,
            inventory,
            &mut split_pre_compute_buf,
        )?;
        let pc_start = exe.pc_start;
        let init_memory = exe.init_memory.clone();
        #[cfg(feature = "tco")]
        let handlers = program
            .instructions_and_debug_infos
            .iter()
            .zip_eq(split_pre_compute_buf.iter_mut())
            .enumerate()
            .map(
                |(slot, (inst_opt, pre_compute))| -> Result<Handler<Ctx>, StaticProgramError> {
                    if let Some((inst, _)) = inst_opt {
                        let pc = program.pc_base + slot as u32 * DEFAULT_PC_STEP;
                        if get_system_opcode_handler::<Ctx>(pc, inst, pre_compute)?.is_some() {
                            Ok(terminate_execute_tco_handler)
                        } else {
                            // unwrap because get_pre_compute_instructions would have errored
                            // already on DisabledOperation
                            let executor = inventory.get_executor(inst.opcode).unwrap();
                            executor.handler(pc, inst, pre_compute)
                        }
                    } else {
                        Ok(unreachable_tco_handler)
                    }
                },
            )
            .collect::<Result<Vec<_>, _>>()?;

        Ok(Self {
            system_config: inventory.config(),
            pre_compute_buf,
            #[cfg(not(feature = "tco"))]
            pre_compute_insns,
            pc_base: program.pc_base,
            pc_start,
            init_memory,
            #[cfg(feature = "tco")]
            pre_compute_max_size,
            #[cfg(feature = "tco")]
            handlers,
        })
    }

    pub fn create_initial_vm_state(&self, inputs: impl Into<Streams>) -> VmState {
        VmState::initial(self.system_config, &self.init_memory, self.pc_start, inputs)
    }

    /// # Safety
    /// - This function assumes that the `pc` is within program bounds - this should be the case if
    ///   the pc is checked to be in bounds before jumping to it.
    /// - The returned slice may not be entirely initialized, but it is the job of each Executor to
    ///   initialize the parts of the buffer that the instruction handler will use.
    #[cfg(feature = "tco")]
    #[inline(always)]
    pub fn get_pre_compute(&self, pc: u32) -> *const u8 {
        debug_assert!(pc >= self.pc_base);
        debug_assert!((pc - self.pc_base).is_multiple_of(DEFAULT_PC_STEP));
        let slot = get_pc_index(pc.wrapping_sub(self.pc_base));
        // SAFETY:
        // - we assume that pc is in bounds
        // - pre_compute_buf is allocated for pre_compute_max_size * program_len bytes, with each
        //   instruction getting pre_compute_max_size bytes
        // - self.pre_compute_buf.ptr is non-null
        // - initialization of the contents of the slice is the responsibility of each Executor
        debug_assert!((slot + 1) * self.pre_compute_max_size <= self.pre_compute_buf.layout.size());
        unsafe {
            self.pre_compute_buf
                .ptr
                .add(slot * self.pre_compute_max_size)
        }
    }

    #[cfg(feature = "tco")]
    #[inline(always)]
    pub fn get_handler(&self, pc: u32) -> Option<Handler<Ctx>> {
        let slot = checked_program_slot(pc, self.pc_base)?;
        self.handlers.get(slot).copied()
    }
}

impl<'a, Ctx> InterpretedInstance<'a, Ctx>
where
    Ctx: MeteredExecutionCtxTrait,
{
    /// Creates an interpreter for metered execution.
    pub fn new_metered<F, E>(
        inventory: &'a ExecutorInventory<E>,
        exe: &VmExe,
        executor_idx_to_air_idx: &[usize],
    ) -> Result<Self, StaticProgramError>
    where
        F: PrimeField32,
        E: MeteredExecutor<F>,
    {
        let program = &exe.program;
        let pre_compute_max_size = get_metered_pre_compute_max_size::<F, _>(program, inventory);
        let mut pre_compute_buf = alloc_pre_compute_buf(program, pre_compute_max_size);
        let mut split_pre_compute_buf =
            split_pre_compute_buf(program, &mut pre_compute_buf, pre_compute_max_size);
        #[cfg(not(feature = "tco"))]
        let pre_compute_insns = get_metered_pre_compute_instructions::<F, Ctx, E>(
            program,
            inventory,
            executor_idx_to_air_idx,
            &mut split_pre_compute_buf,
        )?;

        let pc_start = exe.pc_start;
        let init_memory = exe.init_memory.clone();
        #[cfg(feature = "tco")]
        let handlers = program
            .instructions_and_debug_infos
            .iter()
            .zip_eq(split_pre_compute_buf.iter_mut())
            .enumerate()
            .map(
                |(slot, (inst_opt, pre_compute))| -> Result<Handler<Ctx>, StaticProgramError> {
                    if let Some((inst, _)) = inst_opt {
                        let pc = program.pc_base + slot as u32 * DEFAULT_PC_STEP;
                        if get_system_opcode_handler::<Ctx>(pc, inst, pre_compute)?.is_some() {
                            Ok(terminate_execute_tco_handler)
                        } else {
                            // unwrap because get_pre_compute_instructions would have errored
                            // already on DisabledOperation
                            let executor_idx = inventory.instruction_lookup[&inst.opcode] as usize;
                            let executor = &inventory.executors[executor_idx];
                            let air_idx = executor_idx_to_air_idx[executor_idx];
                            executor.metered_handler(air_idx, pc, inst, pre_compute)
                        }
                    } else {
                        Ok(unreachable_tco_handler)
                    }
                },
            )
            .collect::<Result<Vec<_>, _>>()?;

        Ok(Self {
            system_config: inventory.config(),
            pre_compute_buf,
            #[cfg(not(feature = "tco"))]
            pre_compute_insns,
            pc_base: program.pc_base,
            pc_start,
            init_memory,
            #[cfg(feature = "tco")]
            pre_compute_max_size,
            #[cfg(feature = "tco")]
            handlers,
        })
    }
}

pub(crate) fn alloc_pre_compute_buf(program: &Program, pre_compute_max_size: usize) -> AlignedBuf {
    let buf_len = program.instructions_and_debug_infos.len() * pre_compute_max_size;
    AlignedBuf::uninit(buf_len, pre_compute_max_size)
}

pub(crate) fn split_pre_compute_buf<'a>(
    program: &Program,
    pre_compute_buf: &'a mut AlignedBuf,
    pre_compute_max_size: usize,
) -> Vec<&'a mut [u8]> {
    let buf_len = program.instructions_and_debug_infos.len() * pre_compute_max_size;
    // SAFETY:
    // - pre_compute_buf.ptr was allocated with exactly buf_len bytes
    // - lifetime 'a ensures the returned slices don't outlive the AlignedBuf
    let pre_compute_buf = unsafe { std::slice::from_raw_parts_mut(pre_compute_buf.ptr, buf_len) };
    pre_compute_buf
        .chunks_exact_mut(pre_compute_max_size)
        .collect()
}

/// Executes using function pointers with the trampoline (loop) approach.
///
/// # Safety
/// The `fn_ptrs` pointer to pre-computed buffers that outlive this function.
#[cfg(not(feature = "tco"))]
#[inline(always)]
unsafe fn execute_trampoline<Ctx: ExecutionCtxTrait>(
    exec_state: &mut VmExecState<GuestMemory, Ctx>,
    fn_ptrs: &[PreComputeInstruction<Ctx>],
    pc_base: u32,
) {
    while exec_state
        .exit_code
        .as_ref()
        .is_ok_and(|exit_code| exit_code.is_none())
    {
        if Ctx::should_suspend(exec_state) {
            tracing::debug!("stop because of should_suspend");
            break;
        }
        let pc = exec_state.pc();
        Ctx::on_instruction_start(exec_state, pc);
        let Some(slot) = checked_program_slot(pc, pc_base) else {
            exec_state.exit_code = Err(ExecutionError::PcOutOfBounds(pc));
            break;
        };

        if let Some(inst) = fn_ptrs.get(slot) {
            // SAFETY: pre_compute assumed to live long enough
            unsafe { (inst.handler)(inst.pre_compute, exec_state) };
        } else {
            exec_state.exit_code = Err(ExecutionError::PcOutOfBounds(pc));
        }
    }
}

#[inline(always)]
pub fn get_pc_index(pc: u32) -> usize {
    (pc / DEFAULT_PC_STEP) as usize
}

#[inline(always)]
fn checked_program_slot(pc: u32, pc_base: u32) -> Option<usize> {
    if !pc.is_multiple_of(DEFAULT_PC_STEP) {
        return None;
    }
    let delta = pc.checked_sub(pc_base)?;
    delta
        .is_multiple_of(DEFAULT_PC_STEP)
        .then(|| get_pc_index(delta))
}

/// Bytes allocated according to the given Layout.
/// Careful: this struct implements Send and Sync unsafely. Don't change the underlying data after
/// initialization.git
// @dev: This is duplicate from the openvm crate, but it doesn't seem worth importing `openvm` here
// just for this.
pub(crate) struct AlignedBuf {
    pub ptr: *mut u8,
    pub layout: Layout,
}

unsafe impl Send for AlignedBuf {}
unsafe impl Sync for AlignedBuf {}

impl AlignedBuf {
    /// Allocate a new buffer whose start address is aligned to `align` bytes.
    /// *NOTE* if `len` is zero then a creates new `NonNull` that is dangling and 16-byte aligned.
    pub fn uninit(len: usize, align: usize) -> Self {
        let layout = Layout::from_size_align(len, align).unwrap();
        if layout.size() == 0 {
            return Self {
                ptr: NonNull::<u128>::dangling().as_ptr() as *mut u8,
                layout,
            };
        }
        // SAFETY: `len` is nonzero
        let ptr = unsafe { alloc(layout) };
        if ptr.is_null() {
            handle_alloc_error(layout);
        }
        AlignedBuf { ptr, layout }
    }
}

impl Drop for AlignedBuf {
    fn drop(&mut self) {
        if self.layout.size() != 0 {
            // SAFETY: self.ptr was allocated with self.layout in AlignedBuf::uninit
            unsafe {
                dealloc(self.ptr, self.layout);
            }
        }
    }
}

#[inline(always)]
unsafe fn terminate_execute_impl<CTX: ExecutionCtxTrait>(
    pre_compute: *const u8,
    exec_state: &mut VmExecState<GuestMemory, CTX>,
) {
    let pre_compute: &TerminatePreCompute =
        std::slice::from_raw_parts(pre_compute, size_of::<TerminatePreCompute>()).borrow();
    exec_state.exit_code = Ok(Some(pre_compute.exit_code));
    CTX::on_terminate(exec_state);
}

#[cfg(feature = "tco")]
unsafe fn terminate_execute_tco_handler<CTX: ExecutionCtxTrait>(
    interpreter: &InterpretedInstance<'_, CTX>,
    exec_state: &mut VmExecState<GuestMemory, CTX>,
) {
    let pre_compute = interpreter.get_pre_compute(exec_state.vm_state.pc());
    terminate_execute_impl(pre_compute, exec_state);
}

#[cfg(feature = "tco")]
unsafe fn unreachable_tco_handler<CTX>(
    _: &InterpretedInstance<'_, CTX>,
    exec_state: &mut VmExecState<GuestMemory, CTX>,
) {
    exec_state.exit_code = Err(ExecutionError::Unreachable(exec_state.vm_state.pc()));
}

pub(crate) fn get_pre_compute_max_size<F, E: Executor<F>>(
    program: &Program,
    inventory: &ExecutorInventory<E>,
) -> usize {
    program
        .instructions_and_debug_infos
        .iter()
        .map(|inst_opt| {
            if let Some((inst, _)) = inst_opt {
                if let Some(size) = system_opcode_pre_compute_size(inst) {
                    size
                } else {
                    inventory
                        .get_executor(inst.opcode)
                        .map(|executor| executor.pre_compute_size())
                        .unwrap()
                }
            } else {
                0
            }
        })
        .max()
        .unwrap()
        .next_power_of_two()
}

pub(crate) fn get_metered_pre_compute_max_size<F, E: MeteredExecutor<F>>(
    program: &Program,
    inventory: &ExecutorInventory<E>,
) -> usize {
    program
        .instructions_and_debug_infos
        .iter()
        .map(|inst_opt| {
            if let Some((inst, _)) = inst_opt {
                if let Some(size) = system_opcode_pre_compute_size(inst) {
                    size
                } else {
                    inventory
                        .get_executor(inst.opcode)
                        .map(|executor| executor.metered_pre_compute_size())
                        .unwrap()
                }
            } else {
                0
            }
        })
        .max()
        .unwrap()
        .next_power_of_two()
}

fn system_opcode_pre_compute_size(inst: &Instruction) -> Option<usize> {
    if inst.opcode == SystemOpcode::TERMINATE.global_opcode() {
        return Some(size_of::<TerminatePreCompute>());
    }
    None
}

#[cfg(not(feature = "tco"))]
pub(crate) fn get_pre_compute_instructions<F, Ctx, E>(
    program: &Program,
    inventory: &ExecutorInventory<E>,
    pre_compute: &mut [&mut [u8]],
) -> Result<Vec<PreComputeInstruction<Ctx>>, StaticProgramError>
where
    F: PrimeField32,
    Ctx: ExecutionCtxTrait,
    E: Executor<F>,
{
    let unreachable_handler: ExecuteFunc<Ctx> = |_, exec_state| {
        exec_state.exit_code = Err(ExecutionError::Unreachable(exec_state.pc()));
    };

    program
        .instructions_and_debug_infos
        .iter()
        .zip_eq(pre_compute.iter_mut())
        .enumerate()
        .map(|(i, (inst_opt, buf))| {
            // SAFETY: we cast to raw pointer and then borrow to remove the lifetime. This
            // is safe only in the current context because `buf` comes
            // from `pre_compute_buf` which will outlive the returned
            // `PreComputeInstruction`s.
            let buf: &mut [u8] = unsafe { &mut *(*buf as *mut [u8]) };
            let pre_inst = if let Some((inst, _)) = inst_opt {
                tracing::trace!("get_pre_compute_instruction {inst:?}");
                let pc = program.pc_base + i as u32 * DEFAULT_PC_STEP;
                if let Some(handler) = get_system_opcode_handler(pc, inst, buf)? {
                    PreComputeInstruction {
                        handler,
                        pre_compute: buf.as_ptr(),
                    }
                } else if let Some(executor) = inventory.get_executor(inst.opcode) {
                    PreComputeInstruction {
                        handler: executor.pre_compute(pc, inst, buf)?,
                        pre_compute: buf.as_ptr(),
                    }
                } else {
                    return Err(StaticProgramError::DisabledOperation {
                        pc,
                        opcode: inst.opcode,
                    });
                }
            } else {
                // Dead instruction at this pc
                PreComputeInstruction {
                    handler: unreachable_handler,
                    pre_compute: buf.as_ptr(),
                }
            };
            Ok(pre_inst)
        })
        .collect::<Result<Vec<_>, _>>()
}

#[cfg(not(feature = "tco"))]
pub(crate) fn get_metered_pre_compute_instructions<F, Ctx, E>(
    program: &Program,
    inventory: &ExecutorInventory<E>,
    executor_idx_to_air_idx: &[usize],
    pre_compute: &mut [&mut [u8]],
) -> Result<Vec<PreComputeInstruction<Ctx>>, StaticProgramError>
where
    F: PrimeField32,
    Ctx: MeteredExecutionCtxTrait,
    E: MeteredExecutor<F>,
{
    let unreachable_handler: ExecuteFunc<Ctx> = |_, exec_state| {
        exec_state.exit_code = Err(ExecutionError::Unreachable(exec_state.pc()));
    };
    program
        .instructions_and_debug_infos
        .iter()
        .zip_eq(pre_compute.iter_mut())
        .enumerate()
        .map(|(i, (inst_opt, buf))| {
            // SAFETY: we cast to raw pointer and then borrow to remove the lifetime. This
            // is safe only in the current context because `buf` comes
            // from `pre_compute_buf` which will outlive the returned
            // `PreComputeInstruction`s.
            let buf: &mut [u8] = unsafe { &mut *(*buf as *mut [u8]) };
            let pre_inst = if let Some((inst, _)) = inst_opt {
                tracing::trace!("get_metered_pre_compute_instruction {inst:?}");
                let pc = program.pc_base + i as u32 * DEFAULT_PC_STEP;
                if let Some(handler) = get_system_opcode_handler(pc, inst, buf)? {
                    PreComputeInstruction {
                        handler,
                        pre_compute: buf.as_ptr(),
                    }
                } else if let Some(&executor_idx) = inventory.instruction_lookup.get(&inst.opcode) {
                    let executor_idx = executor_idx as usize;
                    let executor = inventory
                        .executors
                        .get(executor_idx)
                        .expect("ExecutorInventory ensures executor_idx is in bounds");
                    let air_idx = executor_idx_to_air_idx[executor_idx];
                    PreComputeInstruction {
                        handler: executor.metered_pre_compute(air_idx, pc, inst, buf)?,
                        pre_compute: buf.as_ptr(),
                    }
                } else {
                    return Err(StaticProgramError::DisabledOperation {
                        pc,
                        opcode: inst.opcode,
                    });
                }
            } else {
                PreComputeInstruction {
                    handler: unreachable_handler,
                    pre_compute: buf.as_ptr(),
                }
            };
            Ok(pre_inst)
        })
        .collect::<Result<Vec<_>, _>>()
}

fn get_system_opcode_handler<Ctx: ExecutionCtxTrait>(
    pc: u32,
    inst: &Instruction,
    buf: &mut [u8],
) -> Result<Option<ExecuteFunc<Ctx>>, StaticProgramError> {
    if inst.opcode == SystemOpcode::TERMINATE.global_opcode() {
        let pre_compute: &mut TerminatePreCompute = buf.borrow_mut();
        pre_compute.exit_code = inst
            .c
            .checked_as_u32()
            .ok_or(StaticProgramError::InvalidInstruction(pc))?;
        return Ok(Some(terminate_execute_impl));
    }
    Ok(None)
}

/// Errors if exit code is either error or terminated with non-successful exit code.
fn check_exit_code(exit_code: Result<Option<u32>, ExecutionError>) -> Result<(), ExecutionError> {
    let exit_code = exit_code?;
    if let Some(exit_code) = exit_code {
        // This means execution did terminate
        if exit_code != ExitCode::Success as u32 {
            return Err(ExecutionError::FailedWithExitCode(exit_code));
        }
    }
    Ok(())
}

/// Same as [check_exit_code] but errors if program did not terminate.
pub(super) fn check_termination(
    exit_code: Result<Option<u32>, ExecutionError>,
) -> Result<(), ExecutionError> {
    let did_terminate = matches!(exit_code.as_ref(), Ok(Some(_)));
    check_exit_code(exit_code)?;
    match did_terminate {
        true => Ok(()),
        false => Err(ExecutionError::DidNotTerminate),
    }
}

#[cfg(test)]
mod tests {
    use openvm_stark_sdk::p3_baby_bear::BabyBear;

    use super::*;
    use crate::{arch::execution_mode::MeteredCostCtx, system::SystemExecutor};

    fn terminate_exe(pc_base: u32, pc_start: u32) -> VmExe {
        let terminate = Instruction {
            opcode: SystemOpcode::TERMINATE.global_opcode(),
            ..Default::default()
        };
        VmExe::new(Program::new_without_debug_infos(&[terminate], pc_base)).with_pc_start(pc_start)
    }

    #[test]
    fn high_pc_program_uses_relative_table_for_execution() {
        let exe = terminate_exe(MAX_ALLOWED_PC, MAX_ALLOWED_PC);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<ExecutionCtx>::new::<BabyBear, _>(&inventory, &exe)
            .expect("terminate-only program should be statically valid");

        assert_eq!(
            interpreter.pre_compute_buf.layout.size(),
            size_of::<TerminatePreCompute>()
        );
        assert_eq!(
            interpreter.execute(Streams::default()).unwrap().pc(),
            MAX_ALLOWED_PC
        );
    }

    #[test]
    fn high_pc_program_resolves_nonzero_relative_slot() {
        let terminate = Instruction {
            opcode: SystemOpcode::TERMINATE.global_opcode(),
            ..Default::default()
        };
        let program = Program::new_without_debug_infos_with_option(
            &[None, Some(terminate)],
            MAX_ALLOWED_PC - DEFAULT_PC_STEP,
        );
        let exe = VmExe::new(program).with_pc_start(MAX_ALLOWED_PC);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<ExecutionCtx>::new::<BabyBear, _>(&inventory, &exe)
            .expect("terminate-only program should be statically valid");

        assert_eq!(
            interpreter.execute(Streams::default()).unwrap().pc(),
            MAX_ALLOWED_PC
        );
    }

    #[test]
    fn metered_high_pc_program_resolves_nonzero_relative_slot() {
        let terminate = Instruction {
            opcode: SystemOpcode::TERMINATE.global_opcode(),
            ..Default::default()
        };
        let program = Program::new_without_debug_infos_with_option(
            &[None, Some(terminate)],
            MAX_ALLOWED_PC - DEFAULT_PC_STEP,
        );
        let exe = VmExe::new(program).with_pc_start(MAX_ALLOWED_PC);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<MeteredCostCtx>::new_metered::<BabyBear, _>(
            &inventory,
            &exe,
            &[],
        )
        .expect("terminate-only program should be statically valid");

        let (_, state) = interpreter
            .execute_metered_cost(Streams::default(), MeteredCostCtx::new(vec![]))
            .unwrap();
        assert_eq!(state.pc(), MAX_ALLOWED_PC);
    }

    #[test]
    fn metered_high_pc_program_uses_relative_table_for_execution() {
        let exe = terminate_exe(MAX_ALLOWED_PC, MAX_ALLOWED_PC);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<MeteredCostCtx>::new_metered::<BabyBear, _>(
            &inventory,
            &exe,
            &[],
        )
        .expect("terminate-only program should be statically valid");

        assert_eq!(
            interpreter.pre_compute_buf.layout.size(),
            size_of::<TerminatePreCompute>()
        );
        let (_, state) = interpreter
            .execute_metered_cost(Streams::default(), MeteredCostCtx::new(vec![]))
            .unwrap();
        assert_eq!(state.pc(), MAX_ALLOWED_PC);
    }

    #[test]
    fn pc_before_program_base_is_rejected() {
        let exe = terminate_exe(DEFAULT_PC_STEP, 0);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<ExecutionCtx>::new::<BabyBear, _>(&inventory, &exe)
            .expect("terminate-only program should be statically valid");

        assert!(matches!(
            interpreter.execute(Streams::default()),
            Err(ExecutionError::PcOutOfBounds(0))
        ));
    }

    #[test]
    fn misaligned_pc_is_rejected_before_dispatch() {
        let exe = terminate_exe(0, 2);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<ExecutionCtx>::new::<BabyBear, _>(&inventory, &exe)
            .expect("terminate-only program should be statically valid");

        assert!(matches!(
            interpreter.execute(Streams::default()),
            Err(ExecutionError::PcOutOfBounds(2))
        ));
    }

    #[test]
    fn metered_misaligned_pc_is_rejected_before_dispatch() {
        let exe = terminate_exe(0, 2);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<MeteredCostCtx>::new_metered::<BabyBear, _>(
            &inventory,
            &exe,
            &[],
        )
        .expect("terminate-only program should be statically valid");

        assert!(matches!(
            interpreter.execute_metered_cost(Streams::default(), MeteredCostCtx::new(vec![])),
            Err(ExecutionError::PcOutOfBounds(2))
        ));
    }

    #[test]
    fn pc_with_misaligned_delta_from_program_base_is_rejected() {
        let exe = terminate_exe(2, DEFAULT_PC_STEP);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<ExecutionCtx>::new::<BabyBear, _>(&inventory, &exe)
            .expect("terminate-only program should be statically valid");

        assert!(matches!(
            interpreter.execute(Streams::default()),
            Err(ExecutionError::PcOutOfBounds(DEFAULT_PC_STEP))
        ));
    }

    #[test]
    fn misaligned_program_base_is_rejected_before_dispatch() {
        let exe = terminate_exe(2, 2);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<ExecutionCtx>::new::<BabyBear, _>(&inventory, &exe)
            .expect("terminate-only program should be statically valid");

        assert!(matches!(
            interpreter.execute(Streams::default()),
            Err(ExecutionError::PcOutOfBounds(2))
        ));
    }

    #[test]
    fn metered_misaligned_program_base_is_rejected_before_dispatch() {
        let exe = terminate_exe(2, 2);
        let inventory = ExecutorInventory::<SystemExecutor>::new(SystemConfig::default());
        let interpreter = InterpretedInstance::<MeteredCostCtx>::new_metered::<BabyBear, _>(
            &inventory,
            &exe,
            &[],
        )
        .expect("terminate-only program should be statically valid");

        assert!(matches!(
            interpreter.execute_metered_cost(Streams::default(), MeteredCostCtx::new(vec![])),
            Err(ExecutionError::PcOutOfBounds(2))
        ));
    }

    #[test]
    fn terminate_rejects_negative_exit_code() {
        let inst = Instruction {
            opcode: SystemOpcode::TERMINATE.global_opcode(),
            c: InstructionOperand::from_i32(-1),
            ..Default::default()
        };
        let mut pre_compute = TerminatePreCompute { exit_code: 0 };
        // SAFETY: `pre_compute` is live, initialized, and correctly aligned for the full slice.
        let buf = unsafe {
            std::slice::from_raw_parts_mut(
                (&mut pre_compute as *mut TerminatePreCompute).cast(),
                size_of::<TerminatePreCompute>(),
            )
        };

        assert!(matches!(
            get_system_opcode_handler::<ExecutionCtx>(0, &inst, buf),
            Err(StaticProgramError::InvalidInstruction(0))
        ));
    }
}
