name: Guest Library Tests

on:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
#      - "crates/circuits/**"
#      - "crates/vm/**"
#      - "crates/toolchain/**"
#      - "extensions/**"
      - "guest-libs/**"
#      - "Cargo.toml"
      - ".github/workflows/guest-lib-tests.yml"
#      - "crates/sdk/guest/fib/**"

concurrency:
  group: ${{ github.workflow_ref }}-guest-lib-tests-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  OPENVM_SKIP_DEBUG: "1"

jobs:
  integration-tests:
    strategy:
      matrix:
        crate:
          - { name: "sha2", path: "sha2", rvr: false }
          - { name: "keccak256", path: "keccak256", rvr: false }
          - { name: "ff_derive", path: "ff_derive", rvr: false }
          - { name: "k256", path: "k256", rvr: false }
          - { name: "p256", path: "p256", rvr: false }
          - { name: "pairing", path: "pairing", rvr: false }
          - { name: "verify-stark", path: "verify-stark/circuit", rvr: false }
          - { name: "keccak256", path: "keccak256", rvr: true }
        platform:
          - { runner: "64cpu-linux-x64", image: "ubuntu24-full-x64" }
      # Ensure tests run in parallel even if one fails
      fail-fast: false

    runs-on:
      - runs-on=${{ github.run_id }}-guest-lib-tests-${{ github.run_attempt }}-${{ strategy.job-index }}/runner=${{ matrix.platform.runner }}/image=${{ matrix.platform.image }}/extras=s3-cache

    steps:
      - uses: runs-on/action@v2
        with:
          sccache: s3
      - uses: actions/checkout@v5
      - name: Init keccak rvr FFI submodules
        if: matrix.crate.name == 'keccak256' && matrix.crate.rvr == true
        run: |
          git submodule update --init extensions/keccak256/rvr/ffi/openssl
          git submodule update --init extensions/keccak256/rvr/ffi/xkcp
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            - "crates/circuits/**"
            - "crates/vm/**"
            - "crates/toolchain/**"
            - "extensions/**"
            - "guest-libs/${{ matrix.crate.path }}/**"
            - ".github/workflows/guest-lib-tests.yml"
      - name: Skip if no changes
        if: steps.filter.outputs.matched == 'false'
        run: |
          echo "No relevant changes, skipping tests."
          exit 0

      - uses: dtolnay/rust-toolchain@stable
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: taiki-e/install-action@nextest

      - name: Install clang-22 and lld (required for rvr)
        if: matrix.crate.rvr == true
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y lld

      - name: Run ${{ format('{0}{1}', matrix.crate.name, matrix.crate.rvr && '-rvr' || '') }} guest library tests
        working-directory: guest-libs/${{ matrix.crate.path }}
        run: |
          rustup component add rust-src --toolchain nightly-2026-01-18
          EXTRA_ARGS=()
          if [[ "${{ matrix.crate.rvr }}" == 'true' ]]; then
            EXTRA_ARGS+=(--features=rvr)
          elif [[ "${{ matrix.crate.name }}" == "sha2" || "${{ matrix.crate.name }}" == "keccak256" ]]; then
            EXTRA_ARGS+=(--features=aot)
          elif [[ "${{ matrix.crate.name }}" == "pairing" ]]; then
            EXTRA_ARGS+=(--features=bn254,bls12_381,aot -E 'not test(fallback)')
          fi

          cargo nextest run --cargo-profile=fast "${EXTRA_ARGS[@]}" --no-tests=pass --test-threads=1

      - name: sccache stats
        if: always()
        run: sccache --show-stats || true
